### ISSUE TITLE
P4: Student Management > Page title

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#10]
Student Management > Update the page title from “Student” to “Student Management” to match the Submenu's title and to be consistent. (See attached screenshot)
![page-title](https://cloud.githubusercontent.com/assets/3637417/5501963/973112c4-876b-11e4-9b6d-6d1188865b2b.png)

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
Verified.
