### ISSUE TITLE
P2: Application Administration > Exam Dates> When the user clicks on the "Exam Dates" link available in the left navigation menu, he is redirected to the “Exam” page.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#100]
Since the exam dates are handled from the “Exam” page, therefore no need to have a link in the left navigation menu for the “Exam Dates”

**Comment by DrJoeHage** [comment]
Removed Exam Dates from Application Administration menu. @tannourynadine, Please update both FRS and User Guide.

**Comment by tannourynadine** [comment]
Updated the FRS and Admin/User guides.
