### ISSUE TITLE
P1: Application Administrator > Departments > An error message is generated when the user clicks on the "Delete" button.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#103]
The following error message is generated: "Error in deleting Department:undefined" and the user is not able to delete a Department.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that no error message is generated when the user clicks on the "Delete" button, **however a popup delete confirmation dialog is needed to enable the user to choose between canceling or confirming the deletion process.**

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that no error message is generated when the user clicks on the "Delete" button, and a popup delete confirmation dialog is generated to enable the user to choose between canceling or confirming the deletion process.

**Comment by tannourynadine** [comment]
While testing, I encountered this issue again and the user is not able to delete a department. (Error in deleting Department:undefined)

**Comment by RaymondYounan** [comment]
@tannourynadine, 
Can you please specify the steps you are taking to reproduce this issue?

Thanks

**Comment by tannourynadine** [comment]
Closing this issue as it is no longer reproducible
