### ISSUE TITLE
P2: System Administration > Session > An error message is generated when the user tries to create a Session

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#104]
**Steps to Reproduce**
- Select System Administration > Session from the left navigation menu.
- Click on the “Create New Session”  button and fill in all the information.
- Click on the "Save" button.

**Actual Result**
The following error message is generated: "Failure saving the session :Object reference not set to an instance of an object." and the user is not able to create a new session.

**Expected Result**
No error message should be generated and the user should be able to create a new session.

**Comment by DrJoeHage** [comment]
Also an error is generated when the System Administration > Session menu option is selected.
Failure getting sessions from server :Object reference not set to an instance of an object.

**Comment by Rfarran** [comment]
Done

**Comment by tannourynadine** [comment]
An error message is generated when the user clicks on the "Session" link available at the left navigation menu.

**Comment by tannourynadine** [comment]
- Verified that no error message is generated when the user clicks on the session link available in the left navigation menu.
- Verified that the user is able to create and modify a session.
- The other issues are tracked in issue #223.
