### ISSUE TITLE
P2: System Administration > Session > The modify button is not working

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#105]
**Steps to Reproduce**
- Select System Administration > Session from the left navigation menu.
- Click on the “Modify”  button to modify an existing session.

**Actual Result**
The modify button is not working.

**Expected Result**
The modify button should work correctly and the user should be able to update a session successfully.

**Comment by Rfarran** [comment]
Done

**Comment by tannourynadine** [comment]
An error message is generated when the user clicks on the "Session" link available at the left navigation menu.

**Comment by tannourynadine** [comment]
Verified that the "Modify" button is no longer disabled and the user is able to modify  a session.**However, the user is not able to update the Session start and end date.**

**Comment by DrJoeHage** [comment]
@tannourynadine You should create a separate Issue for the inability to edit the Session Start and End Dates. Modify button issue is fixed and should be verified/closed.

**Comment by tannourynadine** [comment]
Verified that the modify button is no longer disabled.
