### ISSUE TITLE
System Administration > Place > No popup delete confirmation dialog is generated when the user clicks on the "Delete" button. 

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#107]
A popup confirmation dialog should be generated when the user clicks on the "Delete" button to enable the user to choose between canceling or confirming the deletion process.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that a popup confirmation dialog is generated when the user clicks on the "Delete" button and the user is able to choose between canceling or confirming the deletion process.
