### ISSUE TITLE
P1: System Administration > Education Grade > An error message is generated when the user clicks on the "Education Grade" link available in the left navigation menu.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#109]
Please find below the generated error message :

![education-grade](https://cloud.githubusercontent.com/assets/3637417/5642392/6956ddd0-9651-11e4-9bcc-12b3de9b7bac.png)

**Comment by RaymondYounan** [comment]
Joe,

The link should be 
http://emis.joe.me:8088/LookupsManagement/EducationStageGrade/Index
instead of 
http://emis.joe.me:8088/LookupsManagement/EducationGrade/Index

**Comment by DrJoeHage** [comment]
In the menu, there are two options:
SubmenuEducGrade
SubmenuEducStageGrade
They are different.

**Comment by RaymondYounan** [comment]
The Educ Grade is now available on 
http://emis.joe.me:8088/LookupsManagement/EducGrade/Index

**Comment by tannourynadine** [comment]
The link of the Education Grade available in the Left navigation menu still needs to be updated.
(currently it is: http://emis.joe.me:8088/LookupsManagement/EducationGrade/Index)

**Comment by DrJoeHage** [comment]
Made the change but error occurs.

**Comment by DrJoeHage** [comment]
Occurs only in LEMIS mode but works fine in EACI mode.

**Comment by DrJoeHage** [comment]
Fixed. @tannourynadine to verify.

**Comment by tannourynadine** [comment]
Verified for the EACI and LEMiS modes the following:
- No error message is generated when the user clicks on the  "Education Grade" link available in the left navigation menu.
- The "Education Grade" is available on the following links:
  -- http://lemis.joe.me:8088/LookupsManagement/EducGrade/Index
  -- http://emis.joe.me:8088/LookupsManagement/EducGrade/Index
- The user is able create, modify and delete an Education Grade with no issues.
