### ISSUE TITLE
P4: Student Management > The Education Type doesn’t appear at the Delete Student page

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#11]
Student Management > The student’s education type doesn’t appear, when the user clicks on the “Delete” button. (See attached screenshot Delete-Student.png)
![delete-student](https://cloud.githubusercontent.com/assets/3637417/5502023/4f1db64e-876c-11e4-998f-f4a978018d7b.png)

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
Verified.
