### ISSUE TITLE
P2: System Administration > Users > Modifying a user’s role, generates an error message

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#110]
**Steps to Reproduce**
- From the left navigation menu, select System Administration > Users.
- Select a user and then click on the “Modify” button.
- Select a role to assign to the user and then click on the save button.

**Actual Result**
 When the user modifies a user’s role, an error message is generated. 

**Expected Result**
 No error message should be generated when the user modifies a user’s role.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Please find below the list of encountered issues:
- An error is generated when the user tries to create a new user .
- An error is generated when the user tries to update a user's role.
- If the user can assign the following roles: Global Admin, System Admins, Application Admins  and Teachers, why they are present more than once at this page? Can you please clarify.

**Comment by tannourynadine** [comment]
Verified that the user is able to modify an existing User. **However, an error is generated when the user tries to create a new user.**

**Comment by DrJoeHage** [comment]
Verified.
