### ISSUE TITLE
Global Administration > Facility Type > The user is not able to create a new Facility Type

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#113]
The following error message is generated when the user click on the “Save Record” button in order to create a new Facility Type: “Error in creating Lookup:Cannot insert the value NULL into column 'FacilityTypeCreatedOnDate', table 'EMIS.dbo.lkupFacilityType'; column does not allow nulls. INSERT fails. The statement has been terminated.”

**Comment by RaymondYounan** [comment]
Joe, 
We need to add (getdate()) in the Default Value or Binding property for columns FacilityTypeCreatedOnDate and FacilityTypeLastModifiedDate in the lkupFacilityType table

**Comment by DrJoeHage** [comment]
Fixed.

**Comment by tannourynadine** [comment]
Verified that the user is able to create a new Facility Type.
