### ISSUE TITLE
List Management > Education Center Type > The user is not able to create a new Education Center Type

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#114]
The following error message is generated when the user click on the “Save Record” button in order to create a new Education Center Type: “Error in creating Lookup:Cannot insert the value NULL into column 'EducCenterTypeCreatedOnDate', table 'EMIS.dbo.lkupEducCenterType'; column does not allow nulls. INSERT fails. The statement has been terminated.”

**Comment by RaymondYounan** [comment]
Joe, 
We need to add (getdate()) in the Default Value or Binding property for columns EducCenterTypeLastModifiedDate and EducCenterTypeCreatedOnDate in the lkupEducCenterType table

**Comment by DrJoeHage** [comment]
Fixed.

**Comment by tannourynadine** [comment]
Verified that the user is able to Create, Edit and Delete an Education Center Type and no error message is generated.
