### ISSUE TITLE
Creating / Updating Records > The error message generated when the maximum field length of allowed characters is exceeded should be updated

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#115]
When creating or updating a record and entering in the “Description” field a value that exceeds the maximum value of allowed characters, the following error message is generated: “Error updating the Lookup:String or binary data would be truncated. The statement has been terminated.”, the error message should be updated to be more accurate. (e.g: Error: The maximum field length is 50 characters)

**Comment by RaymondYounan** [comment]
Joe,
Can we call this an enhancement and leave it for now?

**Comment by DrJoeHage** [comment]
This is a usability enhancement that we should tackle in the future.
