### ISSUE TITLE
List Management > Health Record > The user is not able to create a new Health Record 

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#116]
The following error message is generated when the user click on the “Save Record” button in order to create a new Health Record: “Error in creating Lookup:Cannot insert the value NULL into column 'HealthRecordCreatedOnDate', table 'EMIS.dbo.lkupHealthRecord'; column does not allow nulls. INSERT fails. The statement has been terminated."

**Comment by RaymondYounan** [comment]
Joe, 
We need to add (getdate()) in the Default Value or Binding property for columns HealthRecordLastModifiedDate and HealthRecordCreatedOnDate in the lkupHealthRecord table

**Comment by DrJoeHage** [comment]
Fixed.

**Comment by tannourynadine** [comment]
Verified that the user is able to Create, Edit and Delete a Health Record and no error message is generated.
