### ISSUE TITLE
P1: A popup delete confirmation dialog is needed for several forms to enable the user to choose between canceling or confirming the deletion process.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#117]
A popup delete confirmation dialog is needed for all the forms available under the "Global Administration" and "List Management" menus.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that a popup delete confirmation dialog is generated and the user is able to choose between canceling or confirming the deletion process.
