### ISSUE TITLE
P4:   The message generated after a record is being created, modified or deleted should be updated.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#118]
When creating, updating or deleting a record, the following message is generated: “Lookup created/updated/deleted successfully” (See attached screenshot), the message should be updated to reflect the name of the form in which the record is being manipulated. (e.g: The Education Type is created successfully.)

Note that this issue is reproducible for the forms available under the "Global Administration" and the "List Management" menus.

![message](https://cloud.githubusercontent.com/assets/3637417/5645829/11df2464-967d-11e4-9773-a0890e941352.png)

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
The user is able to create a record , however modifying and deleting a record generates an error message.
In addition, I encountered the below issues:

**Global Administrator:**
-   Term Status: Incorrect message is displayed while creating, modifying and deleting a record. (e.g: created successfully.)
-   Facility Type: The user is not able to create a new facility.
-   Language : Incorrect message is displayed while creating, modifying and deleting a record. (e.g: created successfully.)
-   Language Proficiency Level: Incorrect message is displayed while creating, modifying and deleting a record. (e.g: created successfully.)

**List Management:**
-   University Major: The user is not able to create a new facility. 
-   Education Center Type: The user is not able to create a new facility.
-   Education Center Gender: Incorrect message is displayed while creating, modifying and deleting a record. (e.g: created successfully.)
-   Registration Status: Incorrect message is displayed while creating, modifying and deleting a record. (e.g: created successfully.)
-   Exam Result: Incorrect message is displayed while creating, modifying and deleting a record. (e.g: created successfully.)
-   Student Education Level: Incorrect message is displayed while creating, modifying and deleting a record. (e.g: created successfully.)
-   Dropout Reason: Incorrect message is displayed while creating, modifying and deleting a record. (e.g: created successfully.)
-   Student Failure Reasons: Incorrect message is displayed while creating, modifying and deleting a record. (e.g: created successfully.)
-   Student Status: Incorrect message is displayed while creating, modifying and deleting a record. (e.g: created successfully.)
-   Health Record: The user is not able to create a new health record.
-   Problem Type: Incorrect message is displayed while creating, modifying and deleting a record. (e.g: created successfully.)
-   Attendance Excuse: Incorrect message is displayed while creating, modifying and deleting a record. (e.g: created successfully.)
-   Marital Status: Incorrect message is displayed while creating, modifying and deleting a record. (e.g: created successfully.)
-   Social Status: Incorrect message is displayed while creating, modifying and deleting a record. (e.g: created successfully.)

**Comment by RaymondYounan** [comment]
Fist part is duplicate of #127 : Solved
Done

**Comment by tannourynadine** [comment]
Verified that for the forms available under the "Global Administration" and the "List Management" menus, the user is able create, modify and delete a record and correct messages are displayed.
