### ISSUE TITLE
P2: Student Management > The user is not able to delete newly created students.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#12]
**Steps to Reproduce**
1.Create a new student by clicking on the “Create” Button.
2.Fill in all the required information and then click on the “Save” button.
3.From the list displaying all students, navigate to the newly created student and then click on the delete button.
4.In the delete confirmation page, click on the “Delete” button.

**Actual Result**
 “An error occurred while processing your request.” Error message is generated when the user tries to delete a newly created student.

**Expected Result**
No error should be generated when the user tries to delete a newly created student and the student should be deleted successfully.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that the user is able to create, update and modify a Student.
