### ISSUE TITLE
Education Centers > Manage Literacy Administrators > The True/False values in the Arabic version of the "Manage Literacy Administrators" form need to be translated.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#120]
![education-center-manage-administrator-ar](https://cloud.githubusercontent.com/assets/3637417/5676773/7ed4ebb8-97e4-11e4-9720-e62e85b84111.png)

**Comment by RaymondYounan** [comment]
Done.
Replaced True/false with icons

**Comment by tannourynadine** [comment]
Verified that the True/false values are replaced with icons.
