### ISSUE TITLE
Centers > Facilities > An error message is generated when the user tries to delete an existing Facility

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#121]
No error message should be generated when the user tries to delete a facility. (See attached Screenshot)

![delete-facility](https://cloud.githubusercontent.com/assets/3637417/5677115/6587a938-97ea-11e4-969d-1a251cb2a7dd.png)

**Comment by RaymondYounan** [comment]
Unable to replicate the error. Neither locally nor online

**Comment by tannourynadine** [comment]
This issue is no longer reproducible.
