### ISSUE TITLE
Centers > Facilities >  Manage Building Service > The "Education Center Type" field needs to be translated in the Arabic form

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#122]
![manage building service](https://cloud.githubusercontent.com/assets/3637417/5677264/6d9c7322-97ec-11e4-8ced-198138de1148.png)

**Comment by RaymondYounan** [comment]
Joe, the Arabic resource file should be updated

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that the "Education Center Type" field is updated to "نوع المركز التعليمي" in the Arabic form.
