### ISSUE TITLE
Centers > Facilities > Manage Center Administrators > The True/False values for the "Has Certification" field needs to be translated in the Arabic form

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#123]
![manage-center-administrator](https://cloud.githubusercontent.com/assets/3637417/5677477/e89c5b66-97ef-11e4-8203-3f35daef7706.png)

**Comment by RaymondYounan** [comment]
Done.
Replaced true/false with icons

**Comment by tannourynadine** [comment]
Verified that the True/False values for the "Has Certification" field are replaced with icons
