### ISSUE TITLE
Centers > School > Manage Building Service > The "Education Center Type" field needs to be translated in the Arabic form

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#124]
![manage-building-services](https://cloud.githubusercontent.com/assets/3637417/5677737/fae9ffaa-97f2-11e4-9ced-2b523d9495d5.png)

**Comment by RaymondYounan** [comment]
Needs to be updated in the Arabic resource file

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that the "Education Center Type" field is updated to "نوع المركز التعليمي" in the Arabic form.
