### ISSUE TITLE
Centers > Schools > Manage School Administrators > The True/False values for the "Has Certification" field needs to be translated in the Arabic form 

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#125]
![school-administrators](https://cloud.githubusercontent.com/assets/3637417/5677807/ec0c8650-97f3-11e4-99d2-affe6b8f857c.png)

**Comment by RaymondYounan** [comment]
Done.
Replaced the true/false by icons

**Comment by tannourynadine** [comment]
Verified that the True/False values for the "Has Certification" field are replaced with icons in both the Arabic and English forms
