### ISSUE TITLE
P4: Application Administration > Grade Section > The delete section needs to be updated in the Arabic form

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#126]
In the Arabic form of the "Delete Grade Section" the following stuff needs to be updated:
- The delete confirmation text needs to be translated
- The position of the "Education Center Term Section Name" in the user interface is not correct and needs be updated. (See Attached screenshot)
- The "Delete" and "Back to List" buttons needs to be translated.

![delet-grade-section](https://cloud.githubusercontent.com/assets/3637417/5678419/f6354098-97fa-11e4-83a1-77a726d182dd.png)

**Comment by RaymondYounan** [comment]
Done points 1 and 3

**Comment by tannourynadine** [comment]
Verified that the delete confirmation text, the "Delete" and "Back to List" buttons are translated.

**Still pending:**
- The position of the "Education Center Term Section Name" in the user interface is not correct and needs be updated.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
- Verified that the delete confirmation text, the "Delete" and "Back to List" buttons are translated.
- Verified that the "Education Center Term", "Education Grade", "Section" and "Language" fields are now displayed correctly.
