### ISSUE TITLE
System Administration > School Day > The True/False values for the "is a Weeken Day" needs to be translated in the Arabic form

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#128]
![1](https://cloud.githubusercontent.com/assets/3637417/5681021/00b998b2-981d-11e4-99fb-9fe73bc3105d.png)

**Comment by RaymondYounan** [comment]
Done. Replaced the true/false with check icons

**Comment by tannourynadine** [comment]
Verified that the True/False values for the "is a Weekend Day" are replaced with check icons.
