### ISSUE TITLE
System Administration > Days of the Week > An error message is generated when the user clicks on the delete button in the Arabic form

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#129]
In the English form the user is able to delete a record, however in the Arabic form the user is not able to delete a record and an error message is generated.

![2](https://cloud.githubusercontent.com/assets/3637417/5681136/4134b5c4-981e-11e4-9cd2-9b0b2c0b4009.png)

**Comment by RaymondYounan** [comment]
Done

**Comment by RaymondYounan** [comment]
I also fixed the update. It was creating the same error

**Comment by tannourynadine** [comment]
Verified that no error message is generated when the user tries to delete or update a day of the week.
