### ISSUE TITLE
P4: Student Management > Table Headers

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#13]
Student Management > Remove the last table header since it's displaying a small arrow at the end. (See attached Screenshot)
![students table](https://cloud.githubusercontent.com/assets/3637417/5502186/202abbae-876f-11e4-80cc-a0d606a1f1a2.png)

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
Verified.
