### ISSUE TITLE
System Administration > Days of the Week > The message generated when the user creates, modifies or deletes a day needs to be updated in the Arabic form

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#130]
Create a Day > Update the message from “يوم الأسبوع تم الإنشاء بنجاح” to “تم إنشاء يوم الأسبوع بنجاح”.
Modify a Day > Update the message from “يوم الأسبوع تم التعديل بنجاح” to “تم تعديل يوم الأسبوع بنجاح”.
Delete a Day > Update the message from “يوم الأسبوع تم الإلغاء بنجاح” to “تم إلغاء يوم الأسبوع بنجاح”.

![days of the week](https://cloud.githubusercontent.com/assets/3637417/5700218/62e20cdc-9a42-11e4-8d0a-06276cc9320b.png)

**Comment by RaymondYounan** [comment]
Same issue as #133

**Comment by DrJoeHage** [comment]
I made the changes to the strings so that they read:
يوم الأسبوع - تمت عملية الإنشاء بنجاح
يوم الأسبوع - تمت عملية التعديل بنجاح
يوم الأسبوع - تمت عملية الإلغاء بنجاح

**Comment by tannourynadine** [comment]
Verified that the message generated when the user creates a day of the week is updated from “يوم الأسبوع تم الإنشاء بنجاح” to “يوم الأسبوع - تمت عملية الإنشاء بنجاح”.
**However, an error message is generated when the user tries to update and delete a day of the week and I was not able to verify the other messages.**
