### ISSUE TITLE
System Administration > School Day > Some data is entered incorrectly

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#131]
At the "School Day" form, some existing data is entered without a value for the "Day of the Week" field.

![school day](https://cloud.githubusercontent.com/assets/3637417/5700512/0bab36e0-9a48-11e4-9e35-13f6fb79c703.png)

**Comment by DrJoeHage** [comment]
This is because at one time, the UI allowed the Day of the Week dropdown to be blank. Now, you can no longer enter a blank day of the week.

**Comment by tannourynadine** [comment]
Verified that this issue is no longer reproducible and the user is no longer able to enter a blank day of the week.
