### ISSUE TITLE
P3: Application Administration > Staff Type > The message generated when the user creates, modifies or deletes a staff type needs to be updated in the Arabic form

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#133]
Create a Day > Update the message from “نوع الوظيفة تم الإنشاء بنجاح” to “تم إنشاء نوع الوظيفة بنجاح”.
Modify a Day > Update the message from “نوع الوظيفة تم التعديل بنجاح” to “تم تعديل نوع الوظيفة بنجاح”.
Delete a Day > Update the message from “نوع الوظيفة تم الإلغاء بنجاح” to “تم إلغاء نوع الوظيفة بنجاح”.

**Comment by RaymondYounan** [comment]
Joe, 
Can you please update the lookup Arabic messages so that they make sense without loosing the positioning? maybe they can become 
نوع الوظيفة انشئ بنجاح

**Comment by DrJoeHage** [comment]
I made the changes to the strings so that they read:
نوع الوظيفة - تمت عملية الإنشاء بنجاح
نوع الوظيفة - تمت عملية التعديل بنجاح
نوع الوظيفة - تمت عملية الإلغاء بنجاح

**Comment by tannourynadine** [comment]
Verified that the message generated when the user creates a staff type is updated from “نوع الوظيفة تم الإنشاء بنجاح” to “تنوع الوظيفة - تمت عملية الإنشاء بنجاح”.
**However, an error message is generated when the user tries to update and delete a staff type and I was not able to verify the other messages.**
