### ISSUE TITLE
P2: Education Centers > Manage Literacy Administrators > An error message is generated when the user clicks on the "Delete" button

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#135]
The following error message is generated when the user clicks on the "Delete" button when trying to delete a center administrator: "Error in deleting Center Administrator:Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index"

**Comment by RaymondYounan** [comment]
Unable to replicate the error neither on my machine nor on the live website.

Can you please provide me with detailed steps on how you got the error?

**Comment by tannourynadine** [comment]
Tested this issue on the newly deployed code and found that this issue is no longer reproducible.
