### ISSUE TITLE
P4: Teachers >Teacher Management > Teacher Engagement > Duplicate "Administrative Order No" field is present at the create/edit teacher engagement form

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#136]
![teacher-engament](https://cloud.githubusercontent.com/assets/3637417/5705345/4a5a01b2-9a81-11e4-8a39-43b28bf2c01f.png)

**Comment by DrJoeHage** [comment]
Same bug is entered for the Arabic UI. They should be linked and cross-referenced.

**Comment by DrJoeHage** [comment]
Issues #136 and #146 and #219 are related.

**Comment by RaymondYounan** [comment]
Done.
The first field was actually the TeacherEngagementSeq but it was named wrong.

**Comment by DrJoeHage** [comment]
Verified. @tannourynadine may take screen shots now.

**Comment by tannourynadine** [comment]
Updated the documents with updated screenshots.
