### ISSUE TITLE
P1: Teachers >Teacher Management > Teacher Engagement > The Directorate value is automatically changed to "Ninewa" in the edit mode

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#137]
**Steps to Reproduce**
- Select Teacher from the left navigation menu.
- Select an existing teacher and then click on the "Manage Teacher Engagement" button.
- Click on the Create button
- For the "Directorate ID" select a country different than "Ninewa" and fill in all the information.
- Click on the Save button.
- Click on the "Modify" button for the newly created engagement.

**Actual Result**
The Directorate value is automatically changed to "Ninewa" in the edit mode.

**Expected Result**
The Directorate value should maintain previously saved value in the edit mode.

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
Verified.
