### ISSUE TITLE
P4: Teachers >Teacher Management > Teacher Engagement > Duplicate page title are present at the delete teacher engagement form

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#138]
![teacher-engament-2](https://cloud.githubusercontent.com/assets/3637417/5705552/dcfb6302-9a82-11e4-93fa-659771db71f0.png)

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that only one page title is available at the Delete Teacher form.
