### ISSUE TITLE
P4: Teacher > Teacher Management > An error message should be generated when the user enters an incorrect email format

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#140]
At the create teacher form, an error message should be generated when the user enter an incorrect email format. (e.g: Invalid email address. (example@domain.com))

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Could not verify this issue due to issue #280.

**Comment by tannourynadine** [comment]
Verified that an error message is generated when the user enters an incorrect email format.
