### ISSUE TITLE
P4: Teacher > Teacher Management > An error message should be generated when the user enters letters instead of number in the “Graduation Year” field

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#141]
At the "Create Teacher" form, the user should not be able to enter letters in the “Graduation Year” field.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that the user is no longer able to enter letters in the “Graduation Year” field.
