### ISSUE TITLE
P4: Teachers >Teacher Management > Teacher Engagement > The "Teacher Engagement Separation Date" value is present in bold at the "Teacher Engagement" form

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#142]
All values present at the "Teacher Engagement" form should have the same presentation. (See attached screenshot)

![teacher-engament-3](https://cloud.githubusercontent.com/assets/3637417/5718459/c3cc203a-9b16-11e4-97b2-78cc86ee1d60.png)

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
Verified.
