### ISSUE TITLE
P3: Teachers >Teacher Management > Teacher Engagement > The “Back To All Teachers” button present at the "Manage Teacher Engagement" form is not working correctly

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#143]
When the user click on the “Back To All Teachers” button, he remains at the same page instead of going to the list displaying all teachers. 

![teacher-engament-4](https://cloud.githubusercontent.com/assets/3637417/5718649/c917bc50-9b18-11e4-99e1-54efb96d6718.png)

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
Verified.
