### ISSUE TITLE
P4: Teachers >Teacher Management > Teacher Engagement > At the "Create Teacher Engagement" form, the page title and the "Save" button need to be translated in the Arabic form

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#145]
![teacher-engament-ar-1](https://cloud.githubusercontent.com/assets/3637417/5719281/b90294e6-9b1f-11e4-82e5-66dd5bca9c28.png)

**Comment by DrJoeHage** [comment]
I fixed 10 files which had hard coded English strings. Will be in Friday's build.

**Comment by tannourynadine** [comment]
Verified that at the "Create Teacher Engagement" form, the page title and the "Save" button are translated in the Arabic form.
