### ISSUE TITLE
P4: Teachers >Teacher Management > Teacher Engagement > The "رقم الأمر الإداري" field is present twice in the Arabic form

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#146]
![teacher-engament-ar-2](https://cloud.githubusercontent.com/assets/3637417/5719453/6ac5fad2-9b21-11e4-9ef7-ac69166dde6f.png)

**Comment by DrJoeHage** [comment]
Issues #136 and #146 and #219 are related.

**Comment by RaymondYounan** [comment]
Done.
The first field was actually the TeacherEngagementSeq but it was named wrong.

**Comment by DrJoeHage** [comment]
Verified. @tannourynadine may take screen shots now.
