### ISSUE TITLE
P4: Student Management > Literacy Student Activity > The Session Name doesn’t appear when the user creates a student's activity record.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#15]
The Session Name doesn’t appear at the “Manage Student Activity” page when the user creates a student activity record. (See attached screenshot)

![session-name](https://cloud.githubusercontent.com/assets/3637417/5502473/3d04d04e-8773-11e4-9539-e9ad67901ceb.png)

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
- Verified that the Session Name appears under the "Session Name" column at the “Manage Student Activity”.
- Verified that the user is able to create and modify a student activity record.
- The user is not able to delete a student activity record and this issue is tracked in #218.
