### ISSUE TITLE
P4: Teachers >Teacher Management > Teacher Engagement > At the "Delete Teacher Engagement" form, the page title, the "Back to List" and "Delete" buttons need to be translated in the Arabic form

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#154]
![delete-teacher-engagement-ar](https://cloud.githubusercontent.com/assets/3637417/5721088/d646217e-9b35-11e4-907e-f97dd5263ffd.png)

**Comment by DrJoeHage** [comment]
Fixed for the Friday build.

**Comment by tannourynadine** [comment]
Could not verify this issue due to issue #219

**Comment by DrJoeHage** [comment]
Verified.
