### ISSUE TITLE
P2: Centers > Facilities > Manage Center Administrators > The newly created facility administrator gets erased after the page gets refreshed

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#155]
**Steps to Reproduce**
-   From the left navigation select Centers > Facilities
-   Select a facility and then click on the “Manage Facility Administrator” button.
-   Click on the “Create Center Administrator” button and fill in all the required information.
-   The newly created administrator is displayed in front of the user.
-   Refresh the page.

**Actual Result**
The newly created facility administrator gets erased after the page gets refreshed

**Expected Result**
The newly created facility administrator should not be erased after the page gets refreshed

**Comment by RaymondYounan** [comment]
I couldn't replicate the bug neither on my machine nor on the live site.
You can see the Education Center #1 has already 3 admins that I added using the application
http://emis.joe.me:8088/CenterManagement/ManageCenterAdmin/Index/10/3

**Comment by tannourynadine** [comment]
This issue is similar to the one described in #156.
After retesting the issue today, it was no longer reproducible.
