### ISSUE TITLE
P2: Education Centers > Manage Literacy Administrators > The newly created Education Center Administrator gets erased after the page gets refreshed

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#156]
**Steps to Reproduce**
-   From the left navigation select Centers > Education Center 
-   Select an Education Center and then click on the “Manage Literacy Center Administrator” button.
-   Click on the “Create Center Administrator” button and fill in all the required information.
-   The newly created administrator is displayed in front of the user.
-   Refresh the page

**Actual Result**
The newly created Education Center Administrator gets erased after the page gets refreshed

**Expected Result**
The newly created Education Center Administrator should not be erased after the page gets refreshed

**Comment by RaymondYounan** [comment]
I couldn't replicate the bug neither on my machine nor on the live site.
You can see the Education Center #1 has already 3 admins that I added using the application
http://emis.joe.me:8088/CenterManagement/ManageEducCenterAdmin/Index/1

**Comment by tannourynadine** [comment]
This issue is still reproducible:
-   Select “Al-Houda Literacy Center”  and click on the “Manage Literacy Center Administrators” button.
-   Create a new administrator, and then click on the “Save Center Administrator” button.
-   The Administrator gets created and the URL of the page is the following: http://emis.joe.me:8088/CenterManagement/ManageCenterAdmin/Index/1/2
-   Refresh the page and notice that the administrator is erased.
-   However, if you used the following link you’ll notice that the administrator is created: http://emis.joe.me:8088/CenterManagement/ManageEducCenterAdmin/Index/1
-   The link of the page that appears after an administrator gets created needs to be updated to point to the correct page.

**Comment by DrJoeHage** [comment]
Fixed.

**Comment by tannourynadine** [comment]
- Verified that the newly created administrator won't get erased after the page gets refreshed.
- The link of the page that appears after an administrator gets created is the following:
  http://emis.joe.me:8088/CenterManagement/ManageCenterAdmin/Index/26/2
