### ISSUE TITLE
P2: Global Administration > Country > The country form is missing from the UI

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#157]
![country](https://cloud.githubusercontent.com/assets/3637417/5722516/749bc57c-9b45-11e4-8ed9-2019ec8820a9.png)

**Comment by RaymondYounan** [comment]
Done
link: http://emis.joe.me:8088/GovernmentManagement/Country/Index

**Comment by tannourynadine** [comment]
- Verified that the Country form is now available in the UI
  -Verified that the user is able to create and delete a country, however there are some issues with updating a country. (Please refer to issue #186)
