### ISSUE TITLE
 P2: Global Administration > Currency> The currency form is missing from the UI 

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#158]
![country](https://cloud.githubusercontent.com/assets/3637417/5722540/a85fc8ae-9b45-11e4-9908-da842a108e63.png)

**Comment by RaymondYounan** [comment]
@DrJoeHage : We need to fix the following in the database :
Set CurrencyID as Primary Key instead of CurrencyCodeISO4217

**Comment by RaymondYounan** [comment]
Done
link http://emis.joe.me:8088/LookupsManagement/Currency/Index

**Comment by DrJoeHage** [comment]
I had to also modify the keys in CountryCurrency table.

**Comment by DrJoeHage** [comment]
Changed CurrencyCodeISO4217 to CurrencyID (int)

**Comment by DrJoeHage** [comment]
Pending verification in UI.

**Comment by tannourynadine** [comment]
- Verified that the Currency form is now available in the UI.
- Verified that the user is able to create, edit and delete a currency.
