### ISSUE TITLE
P2: Application Administration > Exam > An error message is generated when the user clicks on the Exam Link available in the left navigation menu

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#159]
No error should be generated and the Exam should be loaded correctly.

![exam-management](https://cloud.githubusercontent.com/assets/3637417/5735815/1e9b2060-9bd5-11e4-9b22-2b158efdacac.png)

**Comment by Rfarran** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that no error message is generated when the user clicks on the Exam Link available in the left navigation menu.
