### ISSUE TITLE
P3: System Administration > Session > An error message is generated when the user clicks on the Session Link available in the left navigation menu

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#160]
No error should be generated.
![session-management](https://cloud.githubusercontent.com/assets/3637417/5735894/e6fb252c-9bd6-11e4-9ae6-0a89662e92d4.png)

**Comment by Rfarran** [comment]
Done

**Comment by tannourynadine** [comment]
An error message is generated when the user clicks on the "Session" link available on the left navigation menu.

**Comment by DrJoeHage** [comment]
I fixed it today. Should be in the Friday build.

**Comment by tannourynadine** [comment]
Verified that no error message is generated when the user clicks on the "Session" link available in the left navigation menu.
