### ISSUE TITLE
 P1: Students > Students Management > Student Study Record > The Education Grade and Session values are automatically changed to their default values in the edit mode

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#162]
**Steps to Reproduce**
-   From the left navigation select Students > Students Management
-   Select an existing student and then click on the " Students Management" button > Literacy Student Study Record
-   Click on the “Create” button and fill in all the required information, and choose a value for the “Education Grade” different than “Grade 1” and for Session choose a value different than "Literacy 2014-2015"
-   Correct information is displayed in front of the user.
-   Now click on the “Modify” button.

**Actual Result**
The Education Grade and Session values are automatically changed to their default values in the edit mode. (The Education Grade value is changed to "Grade 1" and the Session value is changed to "Literacy 2014-2015" )

**Expected Result**
The Education Grade and Session values should maintain previously saved values in the edit mode.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that the Education Grade and Session values maintain previously saved values in the edit mode.
