### ISSUE TITLE
P1: Students > Student Management > An error message is generated when the user tries to delete a student

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#163]
No error should be generated when the user clicks on the delete button.

**Comment by DrJoeHage** [comment]
Deleting a student, teacher, etc. has a ripple effect on the system. How is it handled?

**Comment by RaymondYounan** [comment]
The person objectstatus is set to 2. No action is taken on the other records
Is this ok?

**Comment by tannourynadine** [comment]
- Verified that no error message is generated when the user deletes a Student.
- Verified that the user is able to create, edit and delete a student.
