### ISSUE TITLE
P1: The fields that has a “Drop Down Menu” as a type, automatically changed to their default values in the edit mode and doesn't maintain previously saved values

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#164]
The forms in which this issue is reproducible are listed below:
-   Literacy Student Activity 
-   Student Attendance Record
-   Student Physical Record 
-   Student Problem 
-   Student Health Record 
-   Student Personal Attribute 

**Note that this issue is similar to the one described in #162**

**Comment by RaymondYounan** [comment]
Literacy Student Activity - Done
Student Attendance Record - Done
Student Physical Record - Done
Student Problem - Done
Student Health Record - Done
Student Personal Attribute - Done

**Comment by tannourynadine** [comment]
Verified for the fields that has a “Drop Down Menu” as a type, they maintain previously saved values in edit mode.
- Literacy Student Activity - Verified
- Student Attendance Record - Verified
- Student Physical Record - Verified
- Student Problem - Verified
- Student Health Record - Verified
- Student Personal Attribute - Verified
