### ISSUE TITLE
Students > Student Management > Literacy Student Physical Record > Incorrect Arabic translation is used for the "Student Physical Record Weight (Kg)" field

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#166]
The "Student Physical Record Weight (Kg)" field should be translated to "وزن الطالب والدارس (كلغ)" 

![student-physical-record](https://cloud.githubusercontent.com/assets/3637417/5754641/21a3ee34-9ca4-11e4-8dc4-597d1626bea4.png)

**Comment by DrJoeHage** [comment]
Fixed in the January 16 build.

**Comment by tannourynadine** [comment]
Verified that the "Student Physical Record Weight (Kg)" field is translated to "وزن الطالب والدارس (كلغ)" in the “Manage Literacy Student Physical Record”  form and in the Create/Edit “Student Physical Record” forms.
