### ISSUE TITLE
Students > Student Management > Literacy Student Physical Record > The English text should be removed in the Arabic form

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#167]
The English text that appears next to the "Hearing Specifications Name", "Speech Specifications Name" and the "Vision Specifications Name" fields should be removed since those fields display Arabic content.

![student-physical-record-2](https://cloud.githubusercontent.com/assets/3637417/5754897/36849116-9ca7-11e4-8b01-476711b94bfc.png)

**Comment by DrJoeHage** [comment]
Fixed in January 16 build.

**Comment by tannourynadine** [comment]
Verified that the English text that appears next to the "Hearing Specifications Name", "Speech Specifications Name" and the "Vision Specifications Name" fields is removed in the Arabic form.
