### ISSUE TITLE
P2: Centers > Facilities > The “Facility Founding Date”  field does not get created or updated to the value chosen by the user

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#168]
**Steps to Reproduce**
-   From the left navigation select Centers > Facilities
-   Select a facility and then click on the “Create Facility” button.
-   Fill in all the required information and choose a specific date for the “Facility Founding Date”  field

**Actual Result**
The “Facility Founding Date”  field does not get created or updated to the value chosen by the user

**Expected Result**
The “Facility Founding Date”  field should be created or updated to the value chosen by the user

**Comment by RaymondYounan** [comment]
Done.

**Comment by tannourynadine** [comment]
Verified that the “Facility Founding Date” field gets created and updated to the value chosen by the user.

**However, please find below a list of encountered issues:**
- While creating a facility when the user clicks on the "Save Facility" button, a popup message displaying the date of the “Facility Founding Date” field is generated. (See attached screenshot)
- The time is displayed next to the “Facility Founding Date” field, refreshing the page removes the issue. (See attached screenshot)

![manage-facilities](https://cloud.githubusercontent.com/assets/3637417/5772878/84ed5d90-9d62-11e4-9c9a-efaae4f3c19a.png)
![manage-facilities-2](https://cloud.githubusercontent.com/assets/3637417/5772877/84e6bb70-9d62-11e4-8c0a-917c0215d63e.png)

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
- Verified that the “Facility Founding Date” field gets created and updated to the value chosen by the user.
- Verified that while creating a facility no popup message displaying the date of the “Facility Founding Date” field is generated.
- Verified that the time is no longer displayed next to the “Facility Founding Date” field.
