### ISSUE TITLE
P2: In the Arabic version of the application, there are some pages that need to be translated

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#169]
Please find below the pages where you can find this issue:
- Students > Student Management > Literacy Student Study Record > Delete page.
- Students > Student Management > Literacy Student Activity > Delete page.
  Students > Student Management > Literacy Student Health Record > Delete page.
- Students > Student Management > Literacy Student Personal Attribute > Create, Edit and Delete pages.
- Students > Student Management > Literacy Student Physical Record > Delete page.
- Students > Student Management > Literacy Student Problem > Delete page.
- Teachers > Teacher Engagement > Delete page.

![delete-teacher-engagement-ar](https://cloud.githubusercontent.com/assets/3637417/5759310/9561642e-9cd5-11e4-9bd6-2edc98b702e5.png)
![student-activity](https://cloud.githubusercontent.com/assets/3637417/5759312/956db63e-9cd5-11e4-9a92-7ed5fb864b94.png)
![student-health-record-delete](https://cloud.githubusercontent.com/assets/3637417/5759316/966463bc-9cd5-11e4-90c4-736a7b06ab51.png)
![student-personal-attributes-create](https://cloud.githubusercontent.com/assets/3637417/5759311/95658a0e-9cd5-11e4-97b6-6eba43eb789e.png)
![student-physical-record](https://cloud.githubusercontent.com/assets/3637417/5759313/956f31b2-9cd5-11e4-955e-48b9d259ba9f.png)
![student-problem](https://cloud.githubusercontent.com/assets/3637417/5759314/956ef620-9cd5-11e4-93b6-a4d3329aba2a.png)
![student-study-record](https://cloud.githubusercontent.com/assets/3637417/5759315/957eec10-9cd5-11e4-9f00-fe6e41cba20d.png)

**Comment by RaymondYounan** [comment]
Done.
Also fixed Students > Student Management > Literacy Student Attendance Record > Delete page

**Comment by tannourynadine** [comment]
Verified that the below pages are translated:
- Students > Student Management > Literacy Student Study Record > Delete page.
- Students > Student Management > Literacy Student Activity > Delete page. 
- Students > Student Management > Literacy Student Health Record > Delete page.
- Students > Student Management > Literacy Student Personal Attribute > Create, Edit and Delete pages.
- Students > Student Management > Literacy Student Physical Record > Delete page.
- Students > Student Management > Literacy Student Problem > Delete page.
- Students > Student Management > Literacy Student Attendance Record > Delete page
