### ISSUE TITLE
P3: Student Management > Student Attendance Record > The "No. of Absence Days" field accepts positive and negative numbers.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#17]
The number of days that the student was absent cannot be negative, please restrict the "No. of Absence Days" field to positive numbers.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that the "No. of Absence Days" field no longer accepts negative values and an error message is generated when the user enters a negative number.
