### ISSUE TITLE
P2: System Administration > Place Type > Unable to create a new Place Type

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#172]
I wanted to add Mohafazat as a new place type but I cannot. No Create button and no listing of the existing Place Types. Just a blank page. In the meantime, I will add it in the database table.

**Comment by RaymondYounan** [comment]
This should not be in the UI

**Comment by DrJoeHage** [comment]
@RaymondYounan Hi Ray, I suggest we keep the code as it was but we will not expose the URL in the menu. This way, if we need to add a PlaceType, we will do so by explicitly typing the URL. Agree?

**Comment by RaymondYounan** [comment]
@DrJoeHage Ok.
So we need to update the FRS and the Menus?

**Comment by DrJoeHage** [comment]
Refer to #250

**Comment by tannourynadine** [comment]
Verified that the "Place Type" field is no longer available in the left navigation menu.
