### ISSUE TITLE
P3: Incorrect filtering on Country-related fields

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#173]
In all forms, when a user selects a specific Country from a dropdown, all other lists of the Places should be filtered accordingly: For example, I should not see the mohafazat of Lebanon if I select Iraq as the country in the Add Ministry form.

**Comment by RaymondYounan** [comment]
This was fixed when we are no longer showing all the countries in the dropdown lists

**Comment by tannourynadine** [comment]
Closing this issue based on Raymond comment.
