### ISSUE TITLE
P2: List Management > Building Service > Unable to modify or delete an existing Building Service

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#174]
After modifying an existing Building Service and clicking the Save button, error occurs:

Error updating the Building Service:The conversion of a varchar data type to a datetime data type resulted in an out-of-range value. The statement has been terminated.

**Comment by DrJoeHage** [comment]
This seems to be occurring with all Lookups for MODIFY and DELETE .
Manage Exam Date Status List
Manage Exam Result List

**Comment by RaymondYounan** [comment]
Issue fixed

**Comment by DrJoeHage** [comment]
Verified.
