### ISSUE TITLE
P4: Change background image of the Login page

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#175]
Replace grass image with another one with Iraq logos.

**Comment by DrJoeHage** [comment]
Hi Nadine, Please provide me with a new JPG file as per the dimensions of the attached one. Please use the logos of the Ministry of Education (Baghdad and Kurdistan) and the Flags of Iraq and Kurdistan with photos of children and adults.
![signin-bg-6](https://cloud.githubusercontent.com/assets/9402931/5794206/9becde06-9f6c-11e4-8d11-b37711840e06.jpg)

**Comment by DrJoeHage** [comment]
Thanks @tannourynadine

**Comment by tannourynadine** [comment]
Please find attached a background image that can be used for the login page, let me know if this is okay with you:

![background-emis](https://cloud.githubusercontent.com/assets/3637417/5858418/afdc1516-a25b-11e4-9095-c54b3f4843ba.jpg)

**Comment by DrJoeHage** [comment]
Children in Iraq don't wear white caps. 

Thanks,

Joe

**Comment by tannourynadine** [comment]
Updated the picture:

![background-emis](https://cloud.githubusercontent.com/assets/3637417/5858878/1d181fdc-a25f-11e4-84ea-cf6104f3bdbd.jpg)

**Comment by DrJoeHage** [comment]
Fixed.

**Comment by tannourynadine** [comment]
Verified that the Login picture is updated.
