### ISSUE TITLE
P3: Centers > Education Center Terms applies only for Schools and Education Centers and not Facilities

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#177]
This option should not apply for Facilities. So, filter out Facilities from the Manage Education Center Terms page.

**Comment by RaymondYounan** [comment]
This option applies to Education Centers only. Fixed this way

**Comment by tannourynadine** [comment]
- Verified that in EACI mode, only ALP centers are displayed at the “Education Center Terms” page.
- Verified that in LEMIS mode, only Literacy centers are displayed at the “Education Center Terms” page.
- Verified for both EACI and LEMIS modes that creating, modifying and deleting a center is reflected at the “Education Center Terms” page.
