### ISSUE TITLE
P3: Student Management > Student Physical Record > Incorrect number is displayed for the student’s physical height and weight when the length for the entered number is bigger than 15 characters. 

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#18]
**Steps to Reproduce**
- Navigate to the "Student Physical Record" page of a specific student.
- Click on the "Create" button.
- In the "Student Physical Record Height (cm)" and the "Student Physical Record Weight (Kg)" fields, enter a number with more than 15 characters. (e.g: 1234567891011122)
- Click on the "Save" button.

**Actual Result**
Incorrect number is displayed for the student’s physical height and weight when the length for the entered number is bigger than 15 characters. (see attached screenshot)
**Expected Result**
An error message should be generated when the field length of the student’s physical height and weight exceeds 15 characters.
![incorrect-value](https://cloud.githubusercontent.com/assets/3637417/5503224/44de838c-877d-11e4-8b88-d69ba9e59b35.png)

**Comment by DrJoeHage** [comment]
The maximum for the height (cm) should be set to 300.
The maximum for the weight (kg) should be set to 500.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that the maximum of allowed numbers for the "Height" field is 300 and for the "Weight" field is 500.
