### ISSUE TITLE
P2: Centers > Education Center Terms / Cannot create a new term

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#180]
Click the button "Choose Center to manage Terms"
Notice that there is a "Choose a Center" button again Instead of "Create a Center Term".

**Comment by RaymondYounan** [comment]
Terms can be cloned to created from Global Term. You should create a global term before

**Comment by tannourynadine** [comment]
@DrJoeHage  can you please confirm the current behavior in order to verify and close the issue.

**Comment by DrJoeHage** [comment]
@tannourynadine and @RaymondYounan . So to be clear, the behavior is that Education Center terms cannot be created on their own independently of anything else. The Director of the Education Center will need to select a global term created under Session Terms and then cloned and modified. Correct?

**Comment by RaymondYounan** [comment]
Correct

**Comment by tannourynadine** [comment]
Yes, This is the correct behavior.

**Comment by DrJoeHage** [comment]
@tannourynadine Let's make sure the User Guide and Admin Guide are clear on this. Then, you may close this Issue.

**Comment by tannourynadine** [comment]
I have updated the LEMIS and EACI user guides according to the described behavior.
