### ISSUE TITLE
P4: Application Administration > Grade Section missing one field in listing

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#181]
Education Grade field should be displayed on this page:
http://emis.joe.me:8088/TermManagement/StageSections/Index

should be displayed with the list of Sections to ensure the user selects to Modify or Delete the desired Section.

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
Verified. @RaymondYounan Please call me to discuss Sections because they apply to a specific term in centers.

**Comment by tannourynadine** [comment]
Verified that the "Education Grade" and the "Section" fields are displayed at the "Grade Section" page.
