### ISSUE TITLE
P3: Centers > Education Centers > School Management / Refresh issue with listing page

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#183]
Modify an existing school then Save changes.
Click on Manage School Administrators button to add one.
Notice that we you return to the listing, the old data of the school you had edited earlier is there.
Click Modify for the School and you will see the old data is there.
Click Cancel then reload the page in the Browser.
The updated data re-appears.

**Comment by RaymondYounan** [comment]
This behavior is related to the cashing in the browser. When you are clicking the back button , the browser is still showing the data originally fetched.

**Comment by RaymondYounan** [comment]
@DrJoeHage Can we close this issue?
