### ISSUE TITLE
P2: Centers > Education Center Terms / Wrong Listing

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#184]
The Choose Center to manage Terms form is not listing the Education Centers. Instead, it is listing the Schools and Facilities under the heading Literacy Center.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
- Verified that in EACI mode, only ALP centers are displayed at the “Education Center Terms” page.
- Verified that in LEMIS mode, only Literacy centers are displayed at the “Education Center Terms” page.
- Verified for both EACI and LEMIS modes that creating, modifying and deleting a center is reflected at the “Education Center Terms” page.
