### ISSUE TITLE
P2: Centers > Education Centers > Listing must be filtered based on AppType

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#188]
If AppType is EACI, only ALP Centers should be displayed. Same for LEMIS, only Literacy Centers are to be listed.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified the following:
- In EACI mode, only ALP Centers are displayed.
- In LEMIS mode, only Literacy Centers are displayed.
