### ISSUE TITLE
P4: Student Management > Student Problem > The vertical bar separating the Modify link from the Delete link is missing.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#19]
The vertical bar separating the Modify link from the Delete link is missing, the two links design needs to be consistent across the application. (See attached screenshot)
![vertical-bar](https://cloud.githubusercontent.com/assets/3637417/5503483/1d4f5c6c-8780-11e4-86c8-243e6b1cfda7.png)

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that the vertical bar separating the Modify link from the Delete link is now available.
