### ISSUE TITLE
P3: EACI Students > Student Management >  The "Literacy" word still appears for all the forms displayed when the user clicks on the "Student Management" button.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#190]
![student-management](https://cloud.githubusercontent.com/assets/3637417/5816909/8cc70378-a0ae-11e4-8223-4ee59a3e777e.png)

**Comment by DrJoeHage** [comment]
Fixed. Will show up in next build.

**Comment by tannourynadine** [comment]
Verified that "Literacy" is replaced with "ALP".
