### ISSUE TITLE
P2: Students > Student Management > Creating student must be based on AppType

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#193]
When creating a new Student, the Education Type of the student should be dependent on the AppType. Currently, the Create Student form is always defaulting to Literacy Student.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that the user is able to create, modify and delete a student.
**However, in EACI mode, only ALP Centers should be displayed for the "Education Center" field. And in LEMIS mode, only Literacy Centers should be displayed.**

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
Fix Verified. @tannourynadine may take screen shot of both Literacy and ALP Student.

**Comment by tannourynadine** [comment]
I have updated the EACI FRS, EACI User Guide and LEMIS User Guide accordingly.
