### ISSUE TITLE
P3: EACI Students > Student Management > The create a student form contains a section for "Literacy Student"

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#194]
The "Literacy Student" section should be removed.
Duplicate of #193
![create-student](https://cloud.githubusercontent.com/assets/3637417/5817218/40cecdee-a0b2-11e4-9de1-1da7f0ac2b46.png)

**Comment by DrJoeHage** [comment]
Same as #193

**Comment by tannourynadine** [comment]
Closing this issue since it's a duplicate of #193
