### ISSUE TITLE
P3: EACI Centers > Education Centers > At the create ALP Center, the save button still shows Literacy

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#195]
![center-management](https://cloud.githubusercontent.com/assets/3637417/5817454/b2edb26c-a0b4-11e4-8c0b-1188b6796409.png)

**Comment by DrJoeHage** [comment]
Fixed. Will show in next build.

**Comment by tannourynadine** [comment]
Verified that at the create ALP Center, the "Save Literacy Center" is updated to "Save ALP Center"
