### ISSUE TITLE
P4: EACI Centers > Education Centers Terms > The user interface is displayed incorrectly at the Create Section Form

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#197]
When the user clicks on the "Create" button in order to create a new Section, the user interface is displayed incorrectly. (see attached screenshot.)
![create-section](https://cloud.githubusercontent.com/assets/3637417/5817913/69285150-a0b9-11e4-9a51-092427b42aa2.png)

**Comment by tannourynadine** [comment]
This issue is also reproducible in the following forms:
- Application Administration > Grade Section > Create and Modify Sections
- Application Administration > Session Terms > Modify ALP Education Center Terms > Create and Modify Sections

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that the user interface is displayed correctly at the Create/Modify Section in the below forms:
- Centers > Education Centers Terms > Create and Modify Sections
- Application Administration > Grade Section > Create and Modify Sections
- Application Administration > Session Terms > Modify ALP Education Center Terms > Create and Modify Sections
