### ISSUE TITLE
P4: Students > The Students page description still shows "Literacy"

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#199]
![students-page](https://cloud.githubusercontent.com/assets/3637417/5818718/67042726-a0c0-11e4-9e5c-a27ea0c24530.png)

**Comment by DrJoeHage** [comment]
Fixed.

**Comment by tannourynadine** [comment]
Verified that the Students page description no longer shows the word "Literacy"and it is updated as follows: "Manage students, register students in sessions and terms, and transfer students from sections within an education center or to other education centers. Manage student profiles, attendance, study, physical, and health records. Track student activities, problems, and personal attitudes."
