### ISSUE TITLE
P3: Breadcrum broken

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#2]
Breadcrumb at top of pages is never changing with the page. It always displays:

You are here: Home Dashboard

**Comment by DrJoeHage** [comment]
@tannourynadine We are deferring the implementation of the breadcrumb for a later release. Make sure it is not in any docs or tutorials.

**Comment by tannourynadine** [comment]
Removed the information related to the breadcrumb feature from the admin and user guides.
