### ISSUE TITLE
P4: Student Management >Student Personal Attributes > Duplicate Titles appear on the Create and Modify pages.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#20]
**Steps to Reproduce**
- Click on the "Create" button available on the Student Personal Attributes page.
- Examine the page title

**Actual Result**
Duplicate Titles appear on the Create page. (See attached screenshot)
Please note that this issue is also reproducible on the edit student personal attributes page.
**Expected Result**
One page title should appear on the Create/Modify pages.
![student-personal-attributes-create](https://cloud.githubusercontent.com/assets/3637417/5504842/165f94be-8792-11e4-87c6-c44268e96278.png)
![student-personal-attributes-edit](https://cloud.githubusercontent.com/assets/3637417/5504843/166249c0-8792-11e4-9533-8b03e7d7fbfb.png)

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that one page title appears on the Create/Modify pages.
