### ISSUE TITLE
P4: The Arabic translation for some forms needs to be updated

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#202]
Global  Administration > Currency:
- Create: From “تم إنشاء العملة بنجاح” to “العملة - تمت عملية الإنشاء بنجاح”
- Update: From “تم تعديل العملة بنجاح” to “العملة - تمت عملية التعديل بنجاح”
- Delete: From “تم إلغاء العملة بنجاح” to “العملة - تمت عملية الإلغاء بنجاح”

Global  Administration > Country:
- Create: From “تم إنشاء الدولة بنجاح” to “البلد - تمت عملية الإنشاء بنجاح”
- Update: From “تم تعديل الدولة بنجاح” to “البلد - تمت عملية التعديل بنجاح”
- Delete: From “تم إلغاء الدولة بنجاح” to “البلد- تمت عملية الإلغاء بنجاح”

Application Administration > Staff Type:
- Create: From   “نوع الوظيفة- تمت عملية الإنشاء بنجاح” to “نوع الموظفين - تمت عملية الإنشاء بنجاح”
- Update: From  “نوع الوظيفة- تمت عملية التعديل بنجاح” to “نوع الموظفين - تمت عملية التعديل بنجاح”
- Delete: From “نوع الوظيفة- تمت عملية الإلغاء بنجاح “ to “نوع الموظفين - تمت عملية التعديل بنجاح”

**Comment by DrJoeHage** [comment]
Currency and Country are not like the other items in the list so their error messages are generated differently. As for Staff Type, the translation is Fixed for next build.

**Comment by DrJoeHage** [comment]
@tannourynadine Please validate and close.

**Comment by tannourynadine** [comment]
Verified that the Arabic translation for the "Application Administration > Staff Type" is updated as follows:
- Create: From “نوع الوظيفة- تمت عملية الإنشاء بنجاح” to “نوع الموظفين - تمت عملية الإنشاء بنجاح”
- Update: From “نوع الوظيفة- تمت عملية التعديل بنجاح” to “نوع الموظفين - تمت عملية التعديل بنجاح”
- Delete: From “نوع الوظيفة- تمت عملية الإلغاء بنجاح “ to “نوع الموظفين - تمت عملية التعديل بنجاح”
