### ISSUE TITLE
P2: System Administration > User Status > An error is generated when the user clicks on the "User Status" Link available in the left navigation menu

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#204]
![user-roles](https://cloud.githubusercontent.com/assets/3637417/5853369/b74f82ea-a22b-11e4-88dc-789e9412c299.png)

**Comment by RaymondYounan** [comment]
Can you please provide me with the link you are trying to access?

**Comment by tannourynadine** [comment]
When clicking on the "User Status" Link available in the left navigation menu, the "Server Error in"/" Application" page is displayed and has the following URL: http://eaci.joe.me:8088/MenuManagement/ComingSoon/Index

**Comment by RaymondYounan** [comment]
Fixed. The coming soon page will load.
Creating the page is related to issue #273

**Comment by tannourynadine** [comment]
Verified that the "Coming Soon" page is loaded when the user clicks on the "User Status" Link.
