### ISSUE TITLE
P3: Students > Student Management: Sessions should be restricted by AppType

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#208]
Selecting one student, click on Student Management dropdown menu.
Study Record, Activity, Attendance Record, Physical Record, Problem, Health Record, Personal Attribute. All should have the Sessions and Terms restricted to the AppType.

Actual:
All types of Sessions are displayed for an ALP Student.

Expected:
In EACI mode, only ALP Sessions should be displayed.
In LEMIS mode, only Literacy Sessions should be displayed.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified for the following forms that In EACI mode, only ALP Sessions are displayed and In LEMIS mode, only Literacy Sessions are displayed:
- Student Study Record
- Student Activity
- Student Attendance Record
- Student Physical Record
- Student Problem
- Student Health Record
- Student Personal Attribute
