### ISSUE TITLE
P2: Add EducType field as FK in TeacherEngagement table

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#209]
In TeacherEngagement table, add EducType as FK to the lkupEducType table.
This way when Teachers are assigned to Sections, we can filter on only those teachers with the appropriate engagement as opposed to showing EACI teachers as options for Literacy Sections and vice versa.

I will update the table and @RaymondYounan will do the rest.

**Comment by DrJoeHage** [comment]
Table has been updated. @RaymondYounan to update the code next.

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
Verified.
