### ISSUE TITLE
P4: Student Registration > Page Title

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#21]
Update the page title from “Student Section Registration Management” to “Student Registration ” to match the Sub-menu's title and to be consistent. (See attached screenshot)

![student-registration](https://cloud.githubusercontent.com/assets/3637417/5505031/c0875f1a-8794-11e4-959b-8f98e5bf6c0f.png)

**Comment by DrJoeHage** [comment]
Fixed the English and Arabic strings RESX file. Should show up in the next build of January 19.

**Comment by tannourynadine** [comment]
Verified that the page title is updated in both the English and Arabic forms and matches the Sub-menus title.
