### ISSUE TITLE
P3: Centers > Education Center Terms: Centers listing should be restricted by AppType

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#210]
The list of Center to manage their terms should filtered by AppType.

Actual:
All types of Centers are displayed.

Expected:
In EACI mode, only ALP Centers should be displayed.
In LEMIS mode, only Literacy Centers should be displayed.
Schools and Facilities should not be displayed in the above modes.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
-   Verified that in EACI mode, only ALP centers are displayed at the “Education Center Terms” page.
-   Verified that in LEMIS mode, only Literacy centers are displayed at the “Education Center Terms” page.
-   Verified for both EACI and LEMIS modes that creating, modifying and deleting a center is reflected at the “Education Center Terms” page.
