### ISSUE TITLE
P3: Centers > Education Center Terms: Centers listing is showing values from the wrong field

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#211]
The list of Center to manage their terms is showing the Facility Names or School Names and not the ALP Center Names (in EACI mode) and the Literacy Center Names (in LEMIS mode).

Actual:
All types of facilities and schools are displayed.

Expected:
In EACI mode, only ALP Centers should be displayed.
In LEMIS mode, only Literacy Centers should be displayed.
Schools and Facilities should not be displayed in the above modes.

Also see related Issue #210.

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
You are showing the Facilities and Schools. You should show ALP Centers or Literacy Centers.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
- Verified that in EACI mode, only ALP centers are displayed at the “Education Center Terms” page.
- Verified that in LEMIS mode, only Literacy centers are displayed at the “Education Center Terms” page.
- Verified for both EACI and LEMIS modes that creating, modifying and deleting a center is reflected at the “Education Center Terms” page.
