### ISSUE TITLE
P2: Center > Education Centers > Manage Education Center Administrators: Unable to create a new admin

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#213]
When I attempt to save a new Education Center Administrator, I get:
Error in creating Center Admin:An error occurred while updating the entries. See the inner exception for details.

http://eaci.joe.me:8088/CenterManagement/ManageEducCenterAdmin/Index/9

**Comment by RaymondYounan** [comment]
This happened after the merger of StaffAssignment and StaffAssignedTo tables.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that the user is able create, modify and delete an Education Center Administrator and no error message is generated.
