### ISSUE TITLE
P3: Student Management > Literacy Student Activity > An error message is generated when the user clicks on the “Delete” button

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#218]
No error message should be generated when the user clicks on the “Delete” button and the user should be able to delete a student’s activity

![delete-student activity](https://cloud.githubusercontent.com/assets/3637417/5896743/4f3ef7a6-a543-11e4-94c8-3b4a42a61ff2.png)

**Comment by RaymondYounan** [comment]
Done
Will be available in the next build

**Comment by DrJoeHage** [comment]
Verified.
