### ISSUE TITLE
P3: Teachers >Teacher Management > Teacher Engagement > An error message is generated when the user to create a new engagement

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#219]
No error message should be generated when the user clicks on the "Save" button while creating a new Teacher Engagement.

**Comment by DrJoeHage** [comment]
@RaymondYounan Can you check this? It seems there is a duplicate field on the form generating an error. I had to enter a date in the duplicate field to make it save the Teacher Engagement.
![teacher-engagement](https://cloud.githubusercontent.com/assets/9402931/6091236/bc541b72-aea9-11e4-8e3e-b6359c0e1eba.jpg)

**Comment by DrJoeHage** [comment]
Issues #136 and #146 and #219 are related.

**Comment by RaymondYounan** [comment]
Done.
The first field was actually the TeacherEngagementSeq but it was named wrong.

**Comment by DrJoeHage** [comment]
Verified. @tannourynadine may take screen shots now.
