### ISSUE TITLE
P1: Student Registration > Unable to perform any action.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#22]
The page buttons are disabled and the user is not able to perform any action.

**Comment by Rfarran** [comment]
Done

**Comment by DrJoeHage** [comment]
@tannourynadine can now validate/document. Please make sure you are logged into the system when you do that.

**Comment by tannourynadine** [comment]
Verified that the buttons on Student Registration form are enabled.
