### ISSUE TITLE
P1: Students > ALP Student Management: Using Literacy attributes instead of ALP attributes 

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#221]
For the EACI mode, you are saving the Student info in the LiteracyStudent table. Instead, you should be using the ALPStudent table as we are tracking different attributes. Must fix this for data entry to start.

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
Fixed. Time for @tannourynadine to take screen shots.

**Comment by tannourynadine** [comment]
Updated the EASCI FRS, EASCI User Guide and LEMIS User Guide documents
