### ISSUE TITLE
P3: Usability issue: Inability to tell which Student is being managed

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#222]
When performing Student Management tasks like Attendance Record, Problems, etc. once you click on the desired choice, you have no clue from there on which student is in question. The student's name should be displayed on the top of the form and listings until the user returns to the Full Student listing page. Otherwise, one small distraction like a phone call or an interruption, and the user loses track of the record he or she was working on.

This also applies to Teachers.

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
Fix Verified. @tannourynadine may proceed with screen shots for Students and Teachers.

**Comment by tannourynadine** [comment]
I have updated the EACI FRS, EACI User Guide and the LEMIS User Guide with updated screenshots for the Students and Teachers forms.
