### ISSUE TITLE
P1: System Administration > Session: App Crashes when trying to create a session

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#223]

**Comment by DrJoeHage** [comment]
Fixed.

**Comment by tannourynadine** [comment]
Verified that no error message is generated when the user clicks on the "Session" link available in the left navigation menu, **however, an error message is generated when the user tries to create a new session.** "Failure saving the session :Object reference not set to an instance of an object."

**Comment by Rfarran** [comment]
The user needs to be logged in

**Comment by tannourynadine** [comment]
Verified that the user is able to create a session, however, the newly created session is automatically created as closed. **Is this behavior acceptable?**
Please find below how section creation should be created as per the FRS:
- Each Session you create has a status; it can be Open for Registration, In Progress, Suspended, Closed, Canceled or Completed. When you create a session, by default you have to specify to what status it belongs. For example if you marked it as “Open for Registration” this means that students’ registration in this session can start, however, if you marked it as “Closed” this means that the session is created but students’ registration cannot proceed.

**Comment by DrJoeHage** [comment]
@tannourynadine The behavior is correct. Newly created sessions should be closed by default to avoid having students registered in them before a given date. Document in User Guide accordingly.

**Comment by tannourynadine** [comment]
I have updated the “EMIS4EACI-FRS-1.2-Draft-03”, “EMIS4EACI-User-Guide-Revision-1.1-Draft-02 “ and “LEMIS-User-Guide-Revision-1.1-Draft-02” documents as follows:
-   I updated the “Creating Academic sessions” section.
-   I’ve removed the following sections: “Marking a Session as “In Progress””, “Marking a Session as “Suspended”” and “Marking a Session as “Canceled”” to match the current behavior.
