### ISSUE TITLE
P3: EACI >  Student Management > Student Attendance Record > Failure of the Attendance Record creation due to no value available for the “Section” field

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#224]
No value for the “Section” field is available and this causing the failure of the Attendance Record creation.

**Comment by RaymondYounan** [comment]
Are you sure there's EACI Sections available in the database?

**Comment by tannourynadine** [comment]
No I'm not sure @RaymondYounan

**Comment by RaymondYounan** [comment]
I added the values to the database. You can now select Section C from the dropdown

**Comment by tannourynadine** [comment]
Verified that the user is now able to create a new  "Attendance Record" and the “Section” field is no longer empty.
