### ISSUE TITLE
P3: EACI >  Student Management > Student Personal Attribute > Unable to create an personal attribute since no value for the “Term” field is available

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#225]
No value for the “Term” field is available and this causing the creation of an empty student personal attribute.

**Comment by RaymondYounan** [comment]
Added Data to the database. You can now select First Term from the drop down list

**Comment by tannourynadine** [comment]
Verified that the user is now able to create a Student Personal Attribute.
