### ISSUE TITLE
P4: Students > Student Management > Literacy Student Study Record > The English text next to the table header should be removed since it’s displaying Arabic content

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#228]
![student study record](https://cloud.githubusercontent.com/assets/3637417/5918146/016c7724-a62e-11e4-9191-7ec84a982eb8.png)

**Comment by DrJoeHage** [comment]
Need to create new string definitions. I will do that and update the code.

**Comment by DrJoeHage** [comment]
Fixed.

**Comment by tannourynadine** [comment]
Verified that the English text available in the table header is removed.
