### ISSUE TITLE
P3: Students > Student Registration > Issues related to this form 

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#229]
**Issue 1:**
- I created the student “Nariman Moghrabi” and in the “Literacy Student” section of the Student creation form, I chose “New Center” for the “Education Center” field.
- Navigate to “Student Registration” form and choose “New Center”, notice that at the “Students In Center” section that the student “Nariman Moghrab” is not displayed. (See attached screenshot)

![student-registration](https://cloud.githubusercontent.com/assets/3637417/5920279/31675d52-a644-11e4-981b-ec37b1456b71.png)

**Issue 2:**
- The “New Center” has “School” as “Literacy Center Type” and the value “New School” for the “School” field.
- Navigate to Application Administration > Session Terms > Select “New School” to manage its terms, notice that it has 2 Terms and each term has an Education Stage Section.
- If you modify the term name, start and end date, the modifications will appear in the Student Registrations page in the “Literacy Session Term” section. However, I was not able to test the underlined part on the attached picture. Can you please provide me with the steps on how to test this?
- Can you please explain to me how “New Term 1” got created in “Literacy 2015” and how “New Term 2” got created in “ALP 2014”? so that I will be able to test them correctly.

![student-registration-2](https://cloud.githubusercontent.com/assets/3637417/5920284/38c50a72-a644-11e4-980e-eaccf3e4e2cd.png)

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
Verified.
