### ISSUE TITLE
P2: Student Transfer > when clicking on the "Student Transfer" link you will redirected to the "Student Registration" page.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#23]
When the user clicks on the "Student Transfer" link available in the left navigation menu, he will redirected to the "Student Registration" page.

**Comment by Rfarran** [comment]
Done

**Comment by DrJoeHage** [comment]
Verified. @tannourynadine can now validate/document this feature.

**Comment by tannourynadine** [comment]
Verified for EACI mode that the Student transfer is working correctly, however Student Transfer is not working correctly for LEMIS mode and this tracked in issue #238.
