### ISSUE TITLE
P4: Teachers > Teacher Section Assignment > Duplicate text is available in the pop up dialogue of the "Add teacher to current section"

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#231]
The same text appear twice in the "Add teacher to current section".

![teacher-section-assignment](https://cloud.githubusercontent.com/assets/3637417/5940270/7ce08c4e-a712-11e4-91da-47fca65c1fea.png)

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
Fixed.
