### ISSUE TITLE
P1: Application Administration > Ministry: Updating a ministry is not updating PlaceID field

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#232]
When you update a ministry, all info is getting saved except the value of the PlaceID as it remains the same in the Address table.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
I was able to verify the following fields: Ministry Name (English), Ministry Name (عربي) and Ministry Name (كوردى). Can you please provide me with the steps on how to verify the other fields. @DrJoeHage

**Comment by DrJoeHage** [comment]
Upon modifying an existing Ministry, error occurs:
Error updating the Ministry:Object reference not set to an instance of an object.

**Comment by RaymondYounan** [comment]
Done.

**Comment by DrJoeHage** [comment]
Verified.
