### ISSUE TITLE
P1: System Administration > Session: When you edit an existing Session Term, data loss occurs

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#233]
System Administration > Session
Modify Terms
Edit an existing term and Save the changes.
When you return, you will see that all Arabic Strings are question marks ??????????????

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
See Related issue #300.

**Comment by DrJoeHage** [comment]
Unable to verify it. When I attempt to save the Term after I edit it, I get the error:
Failure saving the session :String was not recognized as a valid DateTime.

**Comment by RaymondYounan** [comment]
The date error is not reproducible. The Arabic issue was fixed

**Comment by DrJoeHage** [comment]
Still happening

**Comment by RaymondYounan** [comment]
@DrJoeHage, Can you please confirm that this was solved?

**Comment by DrJoeHage** [comment]
@RaymondYounan Seems to work now on creating and modifying terms in an existing Session.
