### ISSUE TITLE
P2: Centers > Education Center Terms > Center Terms: The user is not able to create, modify or delete a term

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#236]
At the manage Center's terms page, the user is not able to create, edit or delete a Term.

**Comment by RaymondYounan** [comment]
Terms are cloned from global ones and cannot be created. Only modified

**Comment by RaymondYounan** [comment]
@tannourynadine Any action still required for this issue?

**Comment by tannourynadine** [comment]
Closing this issue since it was agreed that the current behavior is the correct behavior.
