### ISSUE TITLE
P3: Students > Students Transfer > Incorrect Center name is displayed for the centers that has “Facility” as a Center Type

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#237]
**Steps to Reproduce**
-   From the left  navigation menu, select “Student Transfer” menu.
-   On a different tab open the “Education Centers”.

**Actual Result**
-   For the education centers that have “Facility” as a center type, the center’s name doesn’t appear correctly at the “Student Transfer” page
-   At the “Student Transfer”, notice that the “Erbil ALP Center” has “Erbil Facility 1” as a center, however if you navigate to “Education Centers” page notice that  “Erbil ALP Center” has “Al Anbar Facility”. (See attached screenshots)

**Expected Result**
For the education centers that have “Facility” as a center type, the center’s name should appear correctly at the “Student Transfer” page.

![2015-02-02_16-22-12](https://cloud.githubusercontent.com/assets/3637417/6001878/f3b7ba8a-aaf6-11e4-9710-4764633f8dbd.png)
![2015-02-02_16-23-18](https://cloud.githubusercontent.com/assets/3637417/6001877/f3b74ee2-aaf6-11e4-9fd0-15767a777f18.png)

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
Still reproducible.

**Comment by DrJoeHage** [comment]
Verified.
