### ISSUE TITLE
P2: LEMIS Students > Student Transfers > The user is not able to transfer a student 

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#238]
In LEMIS mode, the user is not able to transfer a student from a literacy center to another. (See attached screenshot)

![student-transfer](https://cloud.githubusercontent.com/assets/3637417/6002192/e8473218-aaf9-11e4-8950-81492973c031.png)

**Comment by RaymondYounan** [comment]
Done
