### ISSUE TITLE
P3: Application Administration > Grade Section > An error message is generated when the user tries to delete a section

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#243]
- No error message should be generated when the user clicks on the "Delete" button and the section should be delete successfully. 
- To see this issue, navigate to Application Administration > Grade Section and then try to delete "Section B", notice that an error message is generated and the section cannot be deleted.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified in LEMIS mode that the user is able create and delete a section, however in EACI mode the user is not able to create a section since no value is available for the "Term" field.

**Comment by RaymondYounan** [comment]
@tannourynadine , Can you please make sure there are available terms in EACI?

**Comment by DrJoeHage** [comment]
@tannourynadine and @RaymondYounan  A section should be deleted only if it has no Teachers assigned to it and no Students registered in it. Please make sure this is how it is documented and it is behaving.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
- Verified that the user is able to delete a section when no Teachers are assigned to it and no Students are registered in it.
- Verified that the user is not able to delete a section when a Teacher is assigned to it and a Student is registered in it.
