### ISSUE TITLE
P3: Application Administration > Section Hours > Incorrect School/Center are displayed for some Education Centers at the  "Section Hours" page 

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#245]
- Al-Karma Literacy Center should display "Baghdad Facility" instead of "City Center"
- Al-Rawda Literacy Center should display "Al-Hussein Municipal Center" instead of "Erbil Facility 2"

![1](https://cloud.githubusercontent.com/assets/3637417/6062903/f6263bcc-ad5b-11e4-8601-9b4582e9e7ea.png)

![2](https://cloud.githubusercontent.com/assets/3637417/6062902/f5d2742e-ad5b-11e4-8b1b-066ddb9e8bc4.png)

**Comment by RaymondYounan** [comment]
Done. 
@DrJoeHage, You need to update the procedure GetEducCentersForUsers as in the latest code checked in
