### ISSUE TITLE
P4: Student Management > Student Physical Record > The error message generated when the user enters a numbers that exceeds the maximum of allowed numbers needs to be translated in the Arabic form.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#246]
![2015-02-06_10-09-07](https://cloud.githubusercontent.com/assets/3637417/6076224/e8f0ed98-ade8-11e4-8e0b-0c2086ca0f0d.png)

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that the error message generated when the user enters a numbers that exceeds the maximum of allowed numbers is translated in the Arabic form.
