### ISSUE TITLE
P4: Student Management > Student Attendance Record > The error message generated when the user enters a negative value for the "No. of Absence Days" field needs to be translated in the Arabic form

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#247]
![1](https://cloud.githubusercontent.com/assets/3637417/6077105/251c9e4c-adf4-11e4-9078-02ddfd4a60f9.png)

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that the error message generated when the user enters a negative value for the "No. of Absence Days" field is translated in the Arabic form.
