### ISSUE TITLE
P3: Student Management > Student Gender Preference not validating gender

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#249]
When defining a student's gender preference for the school, gender must be validated.
As per the FRS, a Male student can only select Male or Mixed.
Whereas, a Female student can only select Female or Mixed. Currently, you are not enforcing these restrictions.

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
Verified.
