### ISSUE TITLE
P4: Teacher Section Assignment > Page Title

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#25]
Update the page title from "Section Teachers Assignment"  to "Teacher Section Assignment" to match the Sub-menu's title and to be consistent. (See attached screenshot)
![teacher-section-assignment](https://cloud.githubusercontent.com/assets/3637417/5505698/fda7c7b6-879b-11e4-81d8-af707397f866.png)

**Comment by DrJoeHage** [comment]
Fixed. Will be reflected in the build of January 19.

**Comment by tannourynadine** [comment]
Verified that the page title is updated from "Section Teachers Assignment" to "Teacher Section Assignment" and matches the Sub-menu's title.
