### ISSUE TITLE
P4: Remove Place Type from left navigation menu

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#250]
I removed Place Type from the left navigation menu. It is still accessible via a UR. I updated the EACI Administrator Guide to reflect this change. @tannourynadine Please make sure User Guide is updated also to exclude Place Type from it.

**Comment by tannourynadine** [comment]
The user guide doesn't contain "Place Type", however it's still available in the left navigation menu please see attached screenshot. 
![place-type](https://cloud.githubusercontent.com/assets/3637417/6123717/b17ef250-b10e-11e4-8018-a0cbac7dcaa3.png)

**Comment by DrJoeHage** [comment]
Fixed.

**Comment by tannourynadine** [comment]
Verified that the "Place Type" field is no longer available in the left navigation menu.
