### ISSUE TITLE
P3: No value is displayed for the “Manage Literacy Student Registrations” field even if the student is registered in a session.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#257]
This issue is reproducible for the following forms:
-   Manage Student Exam Record
-   Manage Student Failure Reason
-   Manage Student Dropout Reason

Please note that the “Manage Student Dropout Reason” form has a useless button displayed at the Create Student Dropout Record page. (See attached screenshot)

![dropout reason](https://cloud.githubusercontent.com/assets/3637417/6127746/348602e2-b137-11e4-8cd1-8a842a3ab48d.png)

**Comment by RaymondYounan** [comment]
Could not replicate: check student Narimane Mortada (ID 12)
