### ISSUE TITLE
P3: Student Management > Student Gender Preference > The "Manage Literacy Student Gender" Drop Down menu doesn't contain "Female" attribute

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#258]
![gender preference](https://cloud.githubusercontent.com/assets/3637417/6128347/96298630-b13d-11e4-8e66-7d5911f70c36.png)

**Comment by RaymondYounan** [comment]
@tannourynadine, since the student is a male he is only allowed to choose Male and Mixed as preference. Although we all like to, but he is not allowed to enroll in a Female class :)

**Comment by tannourynadine** [comment]
Thanks for the clarification @RaymondYounan.
Verified that for male students only "Male" and "Mixed" values are available in the drop down menu and for female students only "Female" and "Mixed" values are available.

**Comment by DrJoeHage** [comment]
Same as #249 .
