### ISSUE TITLE
P3: Issues related to the UI for the Students and teacher forms

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#259]
Please Find Below the list of issues encountered in several forms:
-   Teachers > Teacher Management > Managing one Teacher
-   Students > Students Management > The list displaying all the forms related to student management is not displaying all the forms after the fifth student.
  See attached screenshots.

![students](https://cloud.githubusercontent.com/assets/3637417/6128890/7f3174ba-b142-11e4-8428-d6c0d0813460.png)
![teacher](https://cloud.githubusercontent.com/assets/3637417/6128891/7f33b590-b142-11e4-8950-39635e8a319c.png)

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that the mentioned issues are no longer reproducible.
