### ISSUE TITLE
P4: System Administration > Session > The “Literacy/ALP Education Stage Name” field should be replaced with “Literacy/ALP Education Grade Name”

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#263]
At the "Show Terms" of a session page, the “Literacy/ALP Education Stage Name” field should be replaced with “Literacy/ALP Education Grade Name”.

![2015-02-12_14-28-36](https://cloud.githubusercontent.com/assets/3637417/6167727/f30df02c-b2c6-11e4-8dcd-ab3994be4aa5.png)
![2015-02-12_14-29-43](https://cloud.githubusercontent.com/assets/3637417/6167728/f315cac2-b2c6-11e4-9266-35824e83ea33.png)

**Comment by DrJoeHage** [comment]
Fixed. Will be in Feb 13 build.

**Comment by tannourynadine** [comment]
Verified that the “Literacy/ALP Education Stage Name” field is replaced with “Literacy/ALP Education Grade Name”.
