### ISSUE TITLE
P3: Centers > Education Center Terms > The Education Center Terms is displaying LEMIS and EACI Terms

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#268]
- In EACI mode, navigate to Centers > Education Center Terms > Select "Al-Salam ALP Center" and then click on the "Choose Center to Manage Terms" button.
- Notice that the Term "Joe Term" and other LEMIS Terms are displayed.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that only LEMIS terms are displayed in LEMIS mode and only EACI Terms are displayed in EACI mode.
