### ISSUE TITLE
Education Centers > Create a Literacy Center > The hint text available inside the "Literacy Center Details" and in the "Literacy Center Census No." text fields should be removed.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#27]
The hint text available inside the "Literacy Center Details" and the "Literacy Center Census No." text fields should be removed since it's not clear for the user.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that the hint text available inside the "Literacy Center Details" and the "Literacy Center Census No." text fields is removed.
