### ISSUE TITLE
P2: Kurdish culture not working

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#274]
Clicking on the Kurdish flag causes an error.

Culture is not supported.
Parameter name: name
ku-iq is an invalid culture identifier.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that no error message is generated when the user clicks on the Kurdish flag and the user is taken to the Arabic version of the application.
