### ISSUE TITLE
P4: Statistics > Literacy Rate > In EACI mode, the page title is not available.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#275]
In LEMIS mode the "Literacy Rate" page has the following title: "Literacy Rate by Governorate", however, in EACI mode the page doesn't have a title.(See attached screenshot.)

![statistics](https://cloud.githubusercontent.com/assets/3637417/6282703/cd8179c0-b8e1-11e4-862e-4304cc5a870d.png)

**Comment by RaymondYounan** [comment]
Done
