### ISSUE TITLE
P3: Statistics > Youth Literacy Map > Clicking on the "Youth Literacy Map" link, redirects the user to the "Adult Literacy Map by Governorate"

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#276]
When the user clicks on the "Youth Literacy Map" link, he should be redirected to the "Youth Literacy Map".

**Comment by RaymondYounan** [comment]
@DrJoeHage The Menu item should be updated to Youth instead of Adult
