### ISSUE TITLE
P3: Teachers >Teacher Management > Error messages are displayed when the user clicks on the "Create/Edit Teacher" button.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#280]
By default, when the user clicks on the "Create/Edit Teacher" button error messages for the "Graduation Year" and the "Email" fields are displayed. (See attached screenshots.)

![2015-02-23_9-17-16](https://cloud.githubusercontent.com/assets/3637417/6324010/b0d2e9f6-bb3b-11e4-9cd2-8324abbea5f6.png)

![teacher](https://cloud.githubusercontent.com/assets/3637417/6324009/b0d1032a-bb3b-11e4-8c6a-b6a4720c0ed7.png)

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that no error message for the "Graduation Year" and the "Email" fields is displayed when the user clicks on the "Create/Edit Teacher" button.
