### ISSUE TITLE
P3: Add Person form > The Country field is not displaying the chosen country

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#281]
Create a new person and assign a country to the user. In the "All Persons" form, the country field is displayed empty. 
![2015-02-23_10-19-00](https://cloud.githubusercontent.com/assets/3637417/6324585/95a7ae6a-bb44-11e4-8aad-50ef58266e15.png)

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that the Country field is displaying the chosen country.
