### ISSUE TITLE
P2: Add Person form > An error message is displayed for the "Email" field, when the user clicks on the "Create/Edit Person" button.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#282]
No error message should be displayed for the "Email" field, when the user clicks on the "Create/Edit Person" button.

![2015-02-23_10-34-17](https://cloud.githubusercontent.com/assets/3637417/6324709/6a44274c-bb46-11e4-91ab-ba034df3db0c.png)

**Comment by RaymondYounan** [comment]
Done
