### ISSUE TITLE
P1: A logged in user is not able to see the Top navigation menu and the left navigation menu

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#283]
Please note that switch between languages doesn't remove the issue.

![2015-02-27_11-23-43](https://cloud.githubusercontent.com/assets/3637417/6409888/09aacbfa-be72-11e4-8c15-1da1c0f6ce26.png)

![2015-02-27_11-24-31](https://cloud.githubusercontent.com/assets/3637417/6409887/09a9d416-be72-11e4-9e2b-2008106fd53e.png)

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Encountered this issue today.

**Comment by DrJoeHage** [comment]
Verified that it is fixed.
