### ISSUE TITLE
P2: Student Management > Student Failure Record > In EACI mode, the user is not able to create, modify and delete a Student Failure Record

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#288]
Since the user is not able to register a student in an Exam (related to #226), at the Student Failure Record Form he is not able to chose a value for the "Manage Accelerated Learning Student Registrations" field and therefore he is not able to create a Failure Record.

**Comment by RaymondYounan** [comment]
@tannourynadine: This is not an issue regarding this page.When I added a Student Registration Record and an Exam Record, I was able to create a Student Failure Record

**Comment by tannourynadine** [comment]
@RaymondYounan please device, how can you create a Student Registration record in EACI mode?

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
Verified.
