### ISSUE TITLE
P2: Education Centers Terms > An error message is generated when the user clicks on the "Education Centers Terms" link available in the left navigation menu.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#29]
An error message is generated when the user clicks on the "Education Centers Terms" link available in the left navigation menu.

**Comment by DrJoeHage** [comment]
Works now.

**Comment by tannourynadine** [comment]
Verified that no error message is generated when the user clicks on the "Education Centers Terms" link available in the left navigation menu.
