### ISSUE TITLE
P2: Student Management > Student Dropout Reasons > In LEMIS mode incorrect values are displayed for the "Dropout Reason", "Registration Notes" and the "Manage Literacy Student Registrations" fields

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#290]
Please find below the list of issues encountered while testing:
- There is no field for the dropout reason, however the "Student Dropout Reasons"  form is showing this field with the values entered in "Dropout Notes".
- There is "Registration Notes" field displayed at the "Student Dropout Reasons"  form, however the use doesn't fill this field in the creation mode.
- While creating a Dropout record, incorrect values are displayed for the "Manage Literacy Student Registrations" field. (e.g.: what does e stand for?)

**Comment by RaymondYounan** [comment]
Added the Dropout Notes
Manage Literacy Student Registrations is showing the registration notes
