### ISSUE TITLE
P1: Student Management > App crashes when adding new literacy student without literacy level entered

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#298]
Error message should be displayed when required fields are not entered on form.

**Comment by RaymondYounan** [comment]
Fixed

**Comment by DrJoeHage** [comment]
I just tried to verify this defect by MDIFYING an existing student and removing the Literacy Level and the app crashed:

Cannot insert the value NULL into column 'StudentLiteracyLevelID', table 'EMIS.dbo.LiteracyStudent'; column does not allow nulls. UPDATE fails.
The statement has been terminated. 
  Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

 Exception Details: System.Data.SqlClient.SqlException: Cannot insert the value NULL into column 'StudentLiteracyLevelID', table 'EMIS.dbo.LiteracyStudent'; column does not allow nulls. UPDATE fails.
The statement has been terminated.

Source Error: 

Line 207:                }
Line 208:                db.SaveChanges();
Line 209:                return RedirectToAction("Index");
Line 210:            }
Line 211:

**Comment by RaymondYounan** [comment]
Done
