### ISSUE TITLE
Education Centers > No popup confirmation dialog is generated when the user clicks on the "Delete" button.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#30]
No popup confirmation dialog is generated when the user clicks on the "Delete" button and the user is not able to cancel neither confirm the deletion process.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
A popup confirmation dialog is generated when the user clicks on the "Delete" button and the user is able to cancel or confirm the deletion process.
