### ISSUE TITLE
P3: System Administration > Session > Modify Term causes date error

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#300]
1. Select a session.
2. Show Terms.
3. Modify a term.
4. Edit the term description.
5. Click Save.
   Error is displayed:
   Failure saving the session :String was not recognized as a valid DateTime.

**Comment by DrJoeHage** [comment]
See Related issue #233.

**Comment by RaymondYounan** [comment]
Done
