### ISSUE TITLE
P2: Why can't user modify start and end dates of a Session?

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#307]
User is unable to modify the start and end dates of a session after its creation. Is there a reason as to why this is the case?

**Comment by Rfarran** [comment]
Fixed - added an edit button to the dates that will clear the existing dates to enter new ones

**Comment by Rfarran** [comment]
Note: I could not check in the code yet because it's not connecting
@DrJoeHage  Do not test this until I notify

**Comment by DrJoeHage** [comment]
@Rfarran Waiting for fix.

**Comment by Rfarran** [comment]
@DrJoeHage Checked in

**Comment by DrJoeHage** [comment]
Verified.
