### ISSUE TITLE
P2: Unable to create a new Place Type

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#308]
We had removed the Place Types link from the left menu.
http://lemis.moe.gov.iq:8085/Lists/Index/PlaceType
However, the page does not have the Create New Place Type button.
If this is by design, I need to document how a new place type can be added. Does it need to be done in the DATABASE?

**Comment by RaymondYounan** [comment]
This is by design. No Place Types should be added

**Comment by DrJoeHage** [comment]
Administration Guide updated.
