### ISSUE TITLE
Education Centers > An error message is generated when the user tries to update a literacy center.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#31]
Please find below the error message generated when the user tries to update a literacy center:

Error updating the Literacy Center:An error was reported while committing a database transaction but it could not be determined whether the transaction succeeded or failed on the database server. See the inner exception and http://go.microsoft.com/fwlink/?LinkId=313468 for more information.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
- Tested the create a new literacy center functionality and verified that the entered information appear correctly.
- Tested the delete an existing literacy center functionality and verified that the literacy center no longer appears.
- Tested the update an existing literacy center functionality and verified that the entered information is updated correctly,
  **however when the user tries to update the “Object Status” field, it won’t get updated.**

**Comment by RaymondYounan** [comment]
Removed the Object Status since it is only needed in the back end to manage the status of the record

**Comment by tannourynadine** [comment]
- Tested the create a new literacy center functionality and verified that the entered information appear correctly.
- Tested the delete an existing literacy center functionality and verified that the literacy center no longer appears.
- Tested the update an existing literacy center functionality and verified that the entered information is updated correctly.
- Verified that the “Object Status” field no longer appears in the user interface.
