### ISSUE TITLE
P1: EducCenter form has usability issues

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#315]
Manage Education Center form has some usability issues.
1. Replace the label Center with Facility
The form is at:
http://lemis.moe.gov.iq:8085/CenterManagement/EducCenter/Index
It makes sense to add two radio buttons: <x> School or < > Facility
then depending on the selection you either enable or disable the School drop down or Facility dropdown.
The current behavior is allowing the user to enter both choices concurrently, while defaulting to saving the record in the database as a School.
![emis-issue-315](https://cloud.githubusercontent.com/assets/9402931/10783937/dd3545c6-7d63-11e5-8e5d-c567f0c38dd6.png)

**Comment by RaymondYounan** [comment]
Done, but instead of the radio button, I kept the drop down list
