### ISSUE TITLE
P3: Usability issue with the Manage Building Service - Unknown Facility

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#319]
While creating the building services, the Facility Name should be displayed on the form so that the user is aware what facility he or she are working on.

![form-building-service](https://cloud.githubusercontent.com/assets/9402931/11008379/cc8dabba-84d8-11e5-990a-bc7e765d0401.png)

![manage-building-service-list](https://cloud.githubusercontent.com/assets/9402931/11008278/14203340-84d8-11e5-9d09-7cd64cdd5199.png)

//Same issue applies to Schools and Education Centers.

**Comment by RaymondYounan** [comment]
Done. Added the Facility name in the title
