### ISSUE TITLE
P3: Usability with listing of building services, unable to return to the list of facilities

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#320]
Need to add a Return button, otherwise the user has to keep hitting the browser's back button.
//Same issue applies to Schools and Education Centers.

![manage-building-service-list](https://cloud.githubusercontent.com/assets/9402931/11008482/7df501dc-84d9-11e5-8cac-fcedec40ba15.png)

**Comment by RaymondYounan** [comment]
Done
