### ISSUE TITLE
P3: Usability with listing of Facility Administrators, unable to return to the list of facilities

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#321]
Missing Return button on the form below:

![manage-facility-administrators-list](https://cloud.githubusercontent.com/assets/9402931/11008714/26ebc5fe-84db-11e5-849f-22c1a07f27d8.png)

Also missing the name of the Facility from the Form:

![form-facility-administrator](https://cloud.githubusercontent.com/assets/9402931/11008736/456e2260-84db-11e5-9634-fdd7e0e7d5f0.png)

**Comment by RaymondYounan** [comment]
Done
