### ISSUE TITLE
P3: Usability issue with Teacher Attendance Record listing unable to tell the EducCenter and Dates

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#324]
http://lemis.moe.gov.iq:8085/TeacherManagement/TeacherAttendanceRecord/Index/1

The listing should also include the following 3 additional columns:

Education Center (to the left of Section column)
Teacher Attendance Record Start Date (to the right of Section column)
Teacher Attendance Record Absence Days (to the right of Start Date column)

Also rename the "Education Grade" heading to "Education Grade Section".

![teacher-attendance-record-list](https://cloud.githubusercontent.com/assets/9402931/11014218/f1f3524e-8535-11e5-86d3-9cbe76812259.png)

**Comment by RaymondYounan** [comment]
Done
