### ISSUE TITLE
P3: Usability issue with Teacher Attendance Record form unable to tell the EducCenter and Grade

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#325]
It is clear in the DB that the Section has all the EduCenter and EducGrade info, however this info must be shown on the data entry form because a Teacher may call in sick for one particular section of a grade in a given EducCenter.

Add two fields above the Section field:

Education Center (which should be a lookup and not a dropdown)
Education Grade (as a dropdown)
//All grades that teacher has sections within the EducCenter are shown
//After the grade is selected, only the sections of the selected EducGrade are displayed.

![teacher-attendance-record-form](https://cloud.githubusercontent.com/assets/9402931/11014232/acda6ed0-8536-11e5-9eea-383beee177b7.png)

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
I am seeing All Sections and not just the sections assigned to the Teacher.

**Comment by RaymondYounan** [comment]
Done
