### ISSUE TITLE
P1: Security issue with Menu Display and Page URLs

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#327]
If user enters a URL to a page that belongs to a Global Administrator menu option, the system allows access to the page.

Also, the home page does not hide the options not applicable to the user role.

The below screen shot shows a user logged in as SysAdmin but the Global Administration option is shown in the Dashboard area. However it is not shown in the Left pane and Top menu, which is correct.

![emis_issue_327](https://cloud.githubusercontent.com/assets/9402931/11021861/e382cf78-8657-11e5-8ceb-885973c2a81d.png)

**Comment by Rfarran** [comment]
Done
