### ISSUE TITLE
P1: Security issue with Login and Page URLs

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#328]
Even when a user is not logged in, if the user enters a URL to a page, the data is displayed. Every page in EMIS should check for a valid login.

See screen shot below, where there is no login, no left pane, and no top menu. However, the URL to modify a teacher worked.

![emis_issue_328](https://cloud.githubusercontent.com/assets/9402931/11021898/d8fd8cfe-8658-11e5-9444-89139332882e.png)

**Comment by Rfarran** [comment]
Done

**Comment by DrJoeHage** [comment]
Verified.
