### ISSUE TITLE
P3: Newly created Session must be set to Closed and not as In Progress

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#329]
As per FRS and User Guide, newly created Sessions must be Closed and not In Progress.

Extract text:
Each Session you create has a status; it can be Open for Registration, In Progress, Suspended, Closed, Canceled or Completed. By default, newly created sessions are marked as closed to avoid having students registered in them before a given date.

**Comment by Rfarran** [comment]
Done

**Comment by DrJoeHage** [comment]
Verified.
