### ISSUE TITLE
P2: Problems with Actions allowed to change status of a Session

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#331]
http://lemis.moe.gov.iq:8085/LiteracyManagement/LiteracySession/Index#

If you have a listing of Sessions, when you click on the Actions dropdown menu on the right side, you have several options shown like Open, In Progress, Suspend, Close, and Complete.

If you select each of the options, notice that the popup dialog box would display a different message than the selected option. It would show:

Complete Session
Are you sure you want to commit? (Complete Session)

even though I selected the Close option from the Actions menu.

Please verify all the actions to ensure they do not confuse the user.

**Comment by Rfarran** [comment]
Done

**Comment by DrJoeHage** [comment]
Verified.
