### ISSUE TITLE
P2: Missing CANCEL option from Status of Session

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#332]
Cancel is missing from the Actions menu.
1. Marking a Session as “Open”
   A Session can be marked as “Open” so that students can start enrolling in the session based on their education type.
2. Marking a Session as “In Progress”
   A Session can be marked as “In Progress” when the Academic Session starts and students have finished the registration process. A Session marked as “In Progress” has exams and terms.
3. Marking a Session as “Suspended”
   A Session can be marked as “Suspended” when a condition, fact, or specific circumstances denies students and teachers to attend a Session. (e.g: War, political circumstances…)
4. Marking a Session as “Closed”
   A Session can be marked as “Closed” to make students inaccessible to registration.
5. Marking a Session as “Canceled”
   A Session can be marked as “Canceled” to cancel a session and the session information will no longer exists.
6. Marking a Session as “Completed”
   A Session can be marked as “Completed” if all the Terms of the Session are completed or canceled otherwise; an error message will be generated.

**Comment by Rfarran** [comment]
Done
