### ISSUE TITLE
P1: Administrators are unable to modify the password of a user

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#334]
Must be able to modify/update the password of a user.

**Comment by Rfarran** [comment]
/Account/AdminResetPassword

**Comment by Rfarran** [comment]
Added page: /Account/AdminResetPassword with roles needed either GloAdmin or SysAdmin

**Comment by DrJoeHage** [comment]
I will fix the page to pull the strings out into resources.

**Comment by DrJoeHage** [comment]
@RaymondYounan and @Rfarran Would you please check the AdminResetPassword.cshtml file? I am getting errors because the strings are not being found although I defined them.

http://lsims.moe.gov.iq:8085/Account/AdminResetPassword/

**Comment by Rfarran** [comment]
Modified the resource files and the code (instead of resources.resources.stringname use resources.stringname) this depends on the .cshtml file location

**Comment by DrJoeHage** [comment]
Verified.
