### ISSUE TITLE
P2: Usability issue with dropdown lists not being alphabetized

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#341]
The drop down lists are shown in natural order but they should be listed alphabetically for ease of locating the desired option on the list. This is slowing data entry process.

**Comment by RaymondYounan** [comment]
Done for:
Center, Schools, Facilities, Center Admins, Facility Admins, School Admins, Center Building Service, Facility Building Service, School Building Service 
Country, Department, Directorate, Directorate Oversight, Ministry

**Comment by RaymondYounan** [comment]
Done
