### ISSUE TITLE
P2: Top Menu dropdowns are showing the wrong options in the dashboard and the correct ones in left pane

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#346]
We had fixed this issue in the past but now it is back. If you select the options under Management, they are displaying incorrect hyperlinks in the Dashboard section of the UI.
1. Application Administration is showing a partial list of the Global Administration submenus.
2. Global Administration is showing the Application Administration submenus.
3. System Administration is showing the correct submenus.

**Comment by RaymondYounan** [comment]
Done
