### ISSUE TITLE
P3: Validation Problems with Create (Facility & School & EducCenter) Administrator forms

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#348]
The form has 3 date fields. Only the field "StaffAssignmentStartDate" is required in the table.

ISSUE 1
When you try to save the Form Error in creating School Administrator:String was not recognized as a valid DateTime. The message should be displayed in side the Create Administrator form and not behind it in the listing. The users kept pressing the Add button and wondering why nothing is happening.

ISSUE 2
The form is allowing entering a "Certification Date" with the "Has Certification" checkbox OFF. It should not.

ISSUE 3
The form is allowing entering an "End Date" and is earlier than the "Start Date". End Date must always be GREATER THAN Start Date.

ISSUE 4
The form is allowing entering a "Certification Date" that is greater than TODAY. It should not.

![issue-348](https://cloud.githubusercontent.com/assets/9402931/11296031/8fc34ed0-8f80-11e5-8d1a-089ce6d62200.png)

**Comment by RaymondYounan** [comment]
Issues 2, 3 and 4 done.
@Rfarran Can you check Issue 1

**Comment by Rfarran** [comment]
Issue one done
@RaymondYounan There is an error in the date comparison (the code is comparing strings rather than dates so now all the dates are later than today)

**Comment by Rfarran** [comment]
Done

**Comment by DrJoeHage** [comment]
Verified.
