### ISSUE TITLE
P1: Native Language is missing from the Student form

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#350]
The NativeLanguageID field is a required field in the Person table and is displayed in both Person and Teacher forms. It is missing from the Student Management form. It should be added.

This blocks data entry process.

**Comment by DrJoeHage** [comment]
When a new student is added, the corresponding record in the Person table has the NativeLanguageID field value set to 1.

**Comment by RaymondYounan** [comment]
Done
