### ISSUE TITLE
P2: Student Personal Attributes is displaying wrong strings in English and Arabic

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#360]
http://lemis.moe.gov.iq:8085/StudentManagement/LiteracyStudentPersonalAttributes/Create/12

ISSUE 1
There is a dropdown for is displaying "Not Set", "True", and "False".
Instead, it should be loaded from the lkupLogicalAnswer table as Yes/No.

ISSUE 2
In Arabic, the same strings are displayed in English.

**Comment by RaymondYounan** [comment]
Fixed
