### ISSUE TITLE
P1: Student Personal Attributes is being set at SessionTerm level instead of Session level 

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#361]
The table for StudentPersonalAttribute should be updated along with the UI to point to the SessionID instead of the SessionTermID.

Also, the current form allows the SessionTermID to not be selected. In the revised form, the SessionID must be required.

This is a blocker issue for data entry.

**Comment by RaymondYounan** [comment]
Done. You already made change in the DB

**Comment by DrJoeHage** [comment]
While verifying the fix, I realized that when an existing Personal Attribute record is modified and SAVED for a given student, it is getting removed from the listing. After I checked the database, I realized that somehow the ObjectStatusID is being set to 0 (i.e. inactive).

**Comment by RaymondYounan** [comment]
Done
