### ISSUE TITLE
P4: Manage Administrators listing missing button to return to Center list

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#364]
ISSUE 1
http://lemis.moe.gov.iq:8085/CenterManagement/ManageEducCenterAdmin/Index/2
There is not link to return to the Education Centers page from the Manage Education Center Administrators listing page.

ISSUE 2
http://lemis.moe.gov.iq:8085/CenterManagement/ManageCenterAdmin/Index/2/3
Same applies to Facilities.

ISSUE 3
http://lemis.moe.gov.iq:8085/CenterManagement/ManageSchoolAdmin/Index/1
Same applies to Schools.

**Comment by RaymondYounan** [comment]
Done
