### ISSUE TITLE
P1: Edit Literacy Center form is showing partial list from lkupFacilitySchoolCenterStatus table

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#367]
http://lemis.moe.gov.iq:8085/CenterManagement/EducCenter/Index

The dropdown for the Facility/Center/School Status field is showing only the first record (Active) from the lkupFacilitySchoolCenterStatus table. It should display the complete list.

It works correctly in Schools and Facilities. The status is different for each. The School hosting the Literacy Center may be Active, but the Literacy Center in it could be Inactive.

**Comment by RaymondYounan** [comment]
Done
