### ISSUE TITLE
P1: Implement a lkupStudentClassification table

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#368]
This table is needed for KPIs and statistical analysis. This table helps determine if a Student is NEW to the education system or not.

Values in this table are:
جديد
متسرّب
راسب بالإمتحانات
راسب بسبب الغياب

New
Dropout
Failed in exams
Failed because of absences

I created the table and seeded it with values.

**Comment by DrJoeHage** [comment]
Need to add this field as a FK in the LiteracyStudent and ALPStudent tables. Need to add this dropdown to the Create/Edit Literacy Student and Create/Edit ALP Student forms. It should be a required field.

**Comment by RaymondYounan** [comment]
Done.
Added the fields StudentClassificationID in both ALPStudent and LiteracyStudent tables and linked it to lkupStudentClassification. The script can be found in lkupStudentClassification.sql on Dropbox
