### ISSUE TITLE
P2: After saving a Session Term, ????? are stored instead of Arabic chars in SessionTerm table

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#369]
This is occurring again. Not sure why. I saw it happen on both AR and KU fields. And sometimes in AR field and not KU field. Note that I filled the KU field using Copy/Paste from the AR field.

**Comment by Rfarran** [comment]
Fixed

**Comment by DrJoeHage** [comment]
See #233
