### ISSUE TITLE
P1: Missing ScheduleID, GeneralDirectorateID, and DirectorateID from EducCenter table and form

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#373]
We missed having the ScheduleID, GeneralDirectorateID, and DirectorateID from the EducCenter table and form. I added them to the table as Optional. After you implement them in the UI as dropdowns, they should be set to REQUIRED in the table and UI. Let me know when this is done.

**Comment by RaymondYounan** [comment]
Done. 
Added the field GeneralDirectorateID and linked it to GeneralDirectorate

**Comment by DrJoeHage** [comment]
@RaymondYounan For some reason, the Educ Center listing is no longer showing anything.
http://lsims.moe.gov.iq:8085/CenterManagement/EducCenter/Index

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
I need to re-verify this after #392 is fixed.

**Comment by RaymondYounan** [comment]
#392 is now fixed

**Comment by DrJoeHage** [comment]
Looks good.
