### ISSUE TITLE
P2: Usability issue with Education Center Terms

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#375]
1. Go to Centers > Education Center Terms
2. Click "Choose Center to Manage Terms" for Al-Houda Women Literacy Center

ISSUE 1: Notice on Top the school's name is displayed "Al-Houda Primary School" or the Facility Name

ISSUE 2: The Session should be displayed in the listing as the First Column on the left, otherwise, user will not know which one to edit.

ISSUE 3: List should be sorted by Term Start Date (Earliest date on top)

ISSUE 4: When the Term is modified, the Modify Term dialog should include the Session name as a non-editable string so that the user knows which Session the Term belongs to.

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
@RaymondYounan I made a change to the code. Need to display the EducCenter name above the Session as READ ONLY. I was able to display the ID but we need the Educ_Center_Details_(en_us/ar_iq/ku_iq).

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
Verified
