### ISSUE TITLE
P1: Implement TeacherCitizenshipNo and TeacherResidenceID fields in Teacher table

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#376]
These two fields will be OPTIONAL in the database. However, in the UI, the following logic must be implemented:
1. If Country of Citizenship = 1 (Iraq), then the TeacherCivilStatusNationalID and TeacherCitizenshipNo are required AND the TeacherResidenceID must be NULL. In this case, the FatherCivilStatusNationalID is optional.
1. If Country of Citizenship <> 1 (Any country other than Iraq), then the TeacherResidenceID is required AND the TeacherCivilStatusNationalID and TeacherCitizenshipNo must be NULL. In this case, the FatherCivilStatusNationalID is optional.

I already implemented the fields in the Teacher table and filled them with the appropriate seed data.

**Comment by RaymondYounan** [comment]
Done. 
The Teacher Residence ID is hidden by default

**Comment by DrJoeHage** [comment]
The way you implemented it is buggy. But only showing and hiding the fields, the values are remaining intact and getting stored in the database. You should reset the field values when the nationality is changed. What is happening now is that the database fields are all getting filled with data. The correct behavior is as follows:
For Iraqi nationals, the fields that may contain values are:
TeacherCivilStatusNationalID
TeacherCitizenshipNo
FatherCivilStatusNationalID
For non-Iraqi nations, only one of the fields may contain a value:
TeacherResidenceID

**Comment by RaymondYounan** [comment]
Done
