### ISSUE TITLE
P0: Implement GeneralDirectorate table

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#377]
We need to add a new GeneralDirectorate table. Then, each General Directorate will have several Directorates under it. Each Directorate will have multiple Departments under it.

I already created the table called GeneralDirectorate and populated it.
We will need to update the Directorate table to add the GeneralDirectorateID to it.
The Department table is unaffected as it is already linked to the DirectorateID.

**Comment by RaymondYounan** [comment]
Done.
The link to access the General Directorate is: ///GovernmentManagement/GeneralDirectorate/Index

**Comment by DrJoeHage** [comment]
I implemented it in the MENU table.
