### ISSUE TITLE
P0: Implement lkupEducCenterClassification table

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#378]
Each EducCenter must be classified.
Each classification is linked to one or more EducStage records.

For example, a School classified as Primary may be linked to the following EducStage records:
Primary, Basic, Complementary, Youth, Accelerated Learning Program.

Then, for each EducStage, the School may include all or some of the grades associated with the EducStage in the EducStageGrade table.

Therefore, the following must be implemented:
1. Create and seed the lkupEducCenterClassification table.
2. Add to EducCenter and School a MULTI-SELECT dropdown indicating the EducCenterClassification from the lkupEducCenterClassification table. NOTE: For a LiteracyCenter, the classification will be different than its parent School. Also, it may have multiple classifications, e.g. Primary and Middle, or Primary, Middle, Secondary.
3. Add UI to select multiple EducStage records associated with the EducCenter/School.
4. Add UI to select multiple EducStageGrade records associated with the EducCenter/School.

Above applies to both EducCenter and School.

I created the lkupEducCenterClassification table and filled it with seed data.

**Comment by RaymondYounan** [comment]
I added the table EducCenterClassification to link the tables EducCenter and lkupEducCenterClassification. The table is available on Dropbox (EducCenterClassification.sql). 
Done

**Comment by DrJoeHage** [comment]
@RaymondYounan. I verifief it for the EducCenter. You also need to do the same for School.

**Comment by RaymondYounan** [comment]
Done for School. I added the table SchoolClassification to link between School and lkupEducCenterClassification. Script can be found on Dropbox
