### ISSUE TITLE
P0: Implement School Gender Preference in Student form instead of a separate form

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#380]
Add checkbox to Student form stating the School/Educ Center Gender preference. The StudentGenderPreference table will be removed. By default, each student will have his/her own gender as a preference, in addition if the flag is TRUE, then it will indicate that Student accepts registration in a Mixed School/Educ Center.

I added the field StudentAcceptsMixedClassrooms to the Student table as a BIT and ALLOWS NULLs.

**Comment by RaymondYounan** [comment]
I changed the type of the field StudentAcceptsMixedClassrooms to int and linked it to lkupLogicalAnswer.
Done

**Comment by DrJoeHage** [comment]
@RaymondYounan StudentAcceptsMixedClassrooms in the STUDENT table must be set to NOT NULL. Please advise when you implement this in the UI. I have updated the table.

**Comment by RaymondYounan** [comment]
Done
