### ISSUE TITLE
P0: Implement School Gender at the Sections level

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#387]
I discovered today that in a School or EducCenter of type Mixed, there could be the following scenarios:
1. Male only sections
2. Female only sections
3. Mixed gender sections
So, the School Gender Preference of the Student must be enforced at the Section level.

I added the field EducCenterGenderID to the EducGradeSection table and linked it to the field with same name in the lkupEducCenterGender table.

**Comment by Rfarran** [comment]
Closed
Need to add the following to the DB (script Section Gender Dec 05 2015.txt)

**Comment by DrJoeHage** [comment]
Script updated in SIMS-DB-Full-201512061115.sql and later.

**Comment by DrJoeHage** [comment]
Restrictions of gender are not working properly.
