### ISSUE TITLE
P0: Usability issue with Grade Sections as no EducCenter is visible

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#391]
When attempting to manage Grade Sections, the School or Education Center are an important missing piece of information.

It should be displayed under:

The list of grade sections:
http://lsims.moe.gov.iq:8085/TermManagement/StageSections/Index

and the grade section form:
http://lsims.moe.gov.iq:8085/TermManagement/StageSections/Edit/1

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
Verified.
