### ISSUE TITLE
Remove Field EducCenterClassificationID from School table

### ISSUE THREAD

**Issue by RaymondYounan** [RaymondYounan/LEMIS#396]
There's no longer need to this field since the addition of the table SchoolClassification

**Comment by DrJoeHage** [comment]
@RaymondYounan Are you sure? Both fields are different. A School may be a Primary school. But the classification of the Educ Center occupying it may be Literacy.

**Comment by RaymondYounan** [comment]
Yeah I'm sure, this field was added to be linked with the table lkupEducCenterClassification. 
The Educ Center has its own classification that is independent from the classification of the School.

**Comment by DrJoeHage** [comment]
Got it.
