### ISSUE TITLE
P0: Restrict Section Gender to the School Gender

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#398]
System is allowing Male sections to be created in Female schools.

Restrictions should be passed from:
School & EducCenter
TO
Sections
TO
Student Gender Preferences

School/EducCenter is Male --> Sections for Males only
School/EducCenter is Female --> Sections for Females only
School/EducCenter is Mixed --> Sections for Males, Females, Mixed

**Comment by DrJoeHage** [comment]
@RaymondYounan @Rfarran See #387

**Comment by Rfarran** [comment]
Done

**Comment by DrJoeHage** [comment]
It does not work 100%. See #464 .

**Comment by RaymondYounan** [comment]
@DrJoeHage issue #464 is fixed, I will mark this one as fixed too

**Comment by DrJoeHage** [comment]
Verified.
