### ISSUE TITLE
P0: Teacher Engagements form is missing some fields

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#399]
1. Add GeneralDirectorate dropdown above Directorate dropdown and restrict Directorate dropdown based on GeneralDirectorate selection.
2. Add EducCenter list (dropdown for now to changed to lookup/search form later)
   In LSIMS mode, use the EducCenterID field in the TeacherEngagement table
   In PSIMS mode, use the SchoolID field in the TeacherEngagement table

//Must be filtered on EducType to ensure proper selection.

**Comment by RaymondYounan** [comment]
Done.
Only the list of centers/schools with the correct gender will show

**Comment by DrJoeHage** [comment]
@RaymondYounan Problem is that the list of EducCenters is showing all but should be filtered by EducType and by Directorate. This will reduce it drastically, e.g.I should only be seeing the Literacy ones (EducType=2) and those belonging to DirectorateID = 20.

**Comment by RaymondYounan** [comment]
Done
