### ISSUE TITLE
P2: Teacher Attendance Record form is missing

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#40]
In Teacher Management, we need a Teacher Attendance Record data entry form.

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
Verified. Time for @tannourynadine to take screen shots.

**Comment by tannourynadine** [comment]
Verified that the "Teacher Attendance Record" is now available in the UI and I updated the EACI FRS and the EASCI User Guide and LEMIS User Guide accordingly.
