### ISSUE TITLE
P0: Modify EducCenter or School form is displaying NULL in the Directorate dropdown

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#402]
Although there is a value in the DB for this field, it is showing as NULL when you load an existing EducCenter or School.

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
@RaymondYounan Fixed for EducCenter but not for School and Facility.

**Comment by RaymondYounan** [comment]
Done
