### ISSUE TITLE
P0: Restrict listing of Teachers when doing Section Assignment based on Engagements

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#403]
For each EducCenter or School, when assigning Teachers to Sections, only the Teachers with valid Assignments (Start and End Dates within the range of the Term in which the Section is created) in the EducCenter or School should be displayed and allowed to be assigned a Section.

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
Verified and documented.
