### ISSUE TITLE
P0: Ensure uniqueness of fields in Teacher table

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#405]
TeacherCivilStatusNationalID
TeacherCensusID
TeacherCitizenshipNo

must have unique values to ensure a Teacher has one record.

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
@RaymondYounan Should I make them required in the Table?

**Comment by RaymondYounan** [comment]
No, I changed the design since they can be null in the case of a foreign Teacher

**Comment by DrJoeHage** [comment]
Teacher is not unique message displayed even though the Teacher is unique.

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
It is partially working:
TeacherCensusID
works fine
but
TeacherCivilStatusNationalID
TeacherCitizenshipNo
are allowing duplicates

**Comment by DrJoeHage** [comment]
Each one is individually not allowed to be duplicated, not the combination of all.

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
Verified.
