### ISSUE TITLE
P0: Implement StudentCitizenshipNo and StudentCensusID fields in Student table

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#406]
Add missing StudentCitizenshipNo and StudentCensusID like we did with the Teacher table and implement the same logic that we implemented for Teachers as in Issue #376.

// I added them to the database as NULL allowed.

**Comment by DrJoeHage** [comment]
I already added the fields to the tables and updated the code for the forms and the model. All you need to do is to implement the logic for HIDE and SHOW as you did for Teachers in issue #376.

**Comment by RaymondYounan** [comment]
Done
