### ISSUE TITLE
P0: Ensure uniqueness of fields in Student table

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#407]
StudentCivilStatusNationalID
StudentCensusID
StudentCitizenshipNo

must have unique values to ensure a Student has one record.

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
@RaymondYounan Should I make them required in the Table?

**Comment by RaymondYounan** [comment]
No, I changed the design since they can be null in the case of a foreign student

**Comment by DrJoeHage** [comment]
Student is not unique message displayed even though the Student is unique.

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
Verified.
