### ISSUE TITLE
P0: Creating and Modifying any existing Section causes a crash

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#409]
On EDITING:
http://lsims.moe.gov.iq:8085/TermManagement/StageSections/Edit/9

A referential integrity constraint violation occurred: The property value(s) of 'EducCenterTerm.EducCenterTermID' on one end of a relationship do not match the property value(s) of 'EducGradeSection.EducCenterTermID' on the other end.

On CREATION:
The conversion of a datetime2 data type to a datetime data type resulted in an out-of-range value.
The statement has been terminated.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.Data.SqlClient.SqlException: The conversion of a datetime2 data type to a datetime data type resulted in an out-of-range value.
The statement has been terminated.

**Comment by Rfarran** [comment]
Done

**Comment by DrJoeHage** [comment]
Verified.
