### ISSUE TITLE
P2: Teacher Language Proficiency form is missing

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#41]
In Teacher Management, we need a Teacher Language Proficiency data entry form.

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
Verified. Time for @tannourynadine to take screen shots.

**Comment by tannourynadine** [comment]
Verified that the Teacher Language Proficiency form is now available in the UI and updated the EACI FRS, EACI User Guide and LEMIS User Guide accordingly.
