### ISSUE TITLE
P1: Creating a New Section causes a crash

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#410]
The conversion of a datetime2 data type to a datetime data type resulted in an out-of-range value.
The statement has been terminated.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Data.SqlClient.SqlException: The conversion of a datetime2 data type to a datetime data type resulted in an out-of-range value.
The statement has been terminated.

**Comment by Rfarran** [comment]
Done

**Comment by DrJoeHage** [comment]
Verified.
