### ISSUE TITLE
P4: Page technical problem

### ISSUE THREAD

**Issue by husseinAlsaadi** [RaymondYounan/LEMIS#428]
Drop down problem when scrolling down on literacy section page.

**Comment by DrJoeHage** [comment]
@husseinAlsaadi . Please be more specific. Paste the URL of the page and point us to the area where this problem occurs.

**Comment by husseinAlsaadi** [comment]
During workshop we faced this problem in this page:
http://lsims.esharing.me/LiteracyManagement/LiteracySession/Index

and still most pages, have unnecessary left scrolling.

**Comment by DrJoeHage** [comment]
Not reproducible.
