### ISSUE TITLE
P2: Choosing location preference to avoid selecting same info from UI

### ISSUE THREAD

**Issue by husseinAlsaadi** [RaymondYounan/LEMIS#430]
User should choose province then town then district for first time.

**Comment by DrJoeHage** [comment]
@husseinAlsaadi WHERE?

**Comment by husseinAlsaadi** [comment]
This was suggestion from Ms. Nidal to do it, so user in a town not needs to enter his/her province and then town every time he/she needs to use the program.(like choosing language once).

**Comment by DrJoeHage** [comment]
OK. This is much clearer now. We implemented the User Preference feature that includes all this.
