### ISSUE TITLE
P3: Login button does not work from all pages

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#44]
Login button only works from home page because its URL is constructed incorrectly in the menu option as a relative link. It should work from any page.

**Comment by RaymondYounan** [comment]
Done.
Code of 22-12-2014 (night)

**Comment by DrJoeHage** [comment]
I assume this issue will go away once Logins are enforced.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that the log in button works across different pages of the application
