### ISSUE TITLE
P4: University Definition changing

### ISSUE THREAD

**Issue by husseinAlsaadi** [RaymondYounan/LEMIS#450]
Change "university competence" to "competence".

**Comment by DrJoeHage** [comment]
@husseinAlsaadi Where?

**Comment by husseinAlsaadi** [comment]
I think you changed it to "التحصيل الدراسي"

http://lsims.esharing.me/TeacherManagement/Teachers/Index

**Comment by DrJoeHage** [comment]
@husseinAlsaadi it says الإنجاز الأكاديمي. Is this OK?

**Comment by husseinAlsaadi** [comment]
"التحصيل الدراسي" is more suitable and as they requested.

**Comment by DrJoeHage** [comment]
Done.
