### ISSUE TITLE
Center Management > Facility form is missing Quality, Independence, Ownership, Environment Type fields

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#46]
Center Management > New Facility form is missing Quality, Independence, Ownership, Environment Type fields which were added to the Facility table after eliminating their separate tables.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that the Create/Edit a facility forms contain the following fields: Environment Type, Building Ownership, Building Independence and Building Quality.
