### ISSUE TITLE
P0: Issue with Section Gender picklist when Creating Grade Section 

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#464]
http://lsims.moe.gov.iq:8085/TermManagement/StageSections/Create

Gender picklist is not being updated to reflect the choices based on the School Gender.

However, it works in some cases while Editing an existing section:

http://lsims.moe.gov.iq:8085/TermManagement/StageSections/Edit/30

**Comment by RaymondYounan** [comment]
Only check the opened Sessions

**Comment by RaymondYounan** [comment]
Done. The Gender issue is fixed and it will only get the opened terms

**Comment by DrJoeHage** [comment]
Verified.
