### ISSUE TITLE
P3: Session field missing from Teacher Attendance Form

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#468]
http://lsims.moe.gov.iq:8085/TeacherManagement/TeacherAttendanceRecord/Edit/4

Session is to be shown as the first field on the form to filter the other options based on selected Session.

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
Validated for Teacher: Amer Ali Mohamed Hasan.
