### ISSUE TITLE
P2: Directorate Filtering needed on Teacher Engagements form

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#469]
Currently, all EducCenters are being displayed in the Teacher Engagement form

http://lsims.moe.gov.iq:8085/TeacherManagement/TeacherEngagements/Edit/11

Correct behavior is to show those EducCenters that have a School or Facility in the selected Directorate.

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
Verified

**Comment by DrJoeHage** [comment]
I just realized that it works fine. But, when you load the form the first time, you are loading all the EducCenters and not only the ones belonging to the Directorate. You should apply the filter OnLoad.

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
Verified.
