### ISSUE TITLE
Center Management > School form is missing Quality, Independence, Ownership, Environment Type fields

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#47]
Center Management > New School form is missing Quality, Independence, Ownership, Environment Type fields which were added to the School table after eliminating their separate tables.

**Comment by RaymondYounan** [comment]
Done.

**Comment by tannourynadine** [comment]
Tested the Create/Modify schools features and verified that the forms now include the following fields: Environment Type, Building Ownership, Building Independence and Building Quality.

**Comment by tannourynadine** [comment]
Close #47
