### ISSUE TITLE
P0: Unable to enter a Student or Teacher address information anywhere

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#473]
Can you point me to where we can enter the address info of Students and Teachers? In the FRS, i had the Address ID specified, which is to be retrieved from the Address table. Now, I cannot find anywhere in the UI to enter this information.

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
Well done. Would you please add the Governorate and District dropdowns above the sub-districts dropdown?

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
Verified.
