### ISSUE TITLE
P0: System Crashes - Unable to create Grade Section

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#474]
http://lsims.moe.gov.iq:8085/TermManagement/StageSections/Create/40
Al-Houda Women Literacy Center

Sequence contains no elements

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.InvalidOperationException: Sequence contains no elements

Source Error: 

Line 322:                                l.EducCenterID == id &&
Line 323:                                l.SessionTerm.Session.EducTypeID == ApplicationHelper.EducType).OrderBy("EducCenterTermName_" + culture);
Line 324:                genderId = db.EducCenters.Where(l => l.EducCenterID == id).First<EducCenter>().SchoolGenderID;
Line 325:            }
Line 326:

Source File: c:\Users\joe\Source\Workspaces\EMIS\LEMIS.MVC\Areas\TermManagement\Controllers\StageSectionsController.cs    Line: 324

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
Verified.
