### ISSUE TITLE
P0: Unable to see any data to register students in a section

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#475]
http://lsims.moe.gov.iq:8085/Registration/StudentTerms/TermRoll

For some reason, the 3 new pages work, but no data is displayed on them. There must be some missing data. I have a session with terms, educ center terms, sections for these terms, students for the educ centers, but I cannot see any students to register them in a section.

![emis-issue-475](https://cloud.githubusercontent.com/assets/9402931/13592935/5de9ce6e-e4ff-11e5-8eea-f08fe3815c1b.png)

**Comment by Rfarran** [comment]
Done

**Comment by Rfarran** [comment]
Please make sure to change the three procedures as follows @DrJoeHage 
I sent these already but apparently only the first one was applied

ALTER Procedure [dbo].[GetEducCenterTerms](@EducCenterID int, @EducType int) As Begin 
    Select EducCenterTermID as lctID, EducCenterTermStatusID as lctStatus, 
        EducCenterTermStartDate as startDate, EducCenterTermEndDate as endDate, 
        EducCenterTermName_en_us as lctNameEn, EducCenterTermName_ar_iq as lctNameAr, 
        EducCenterTermName_ku_iq as lctNameKu,  SessionTermName_en_us as lstNameEn, 
        SessionTermName_ar_iq as lstNameAr, SessionTermName_ku_iq as lstNameKu,  
        TermName_en_us as tNameEn, TermName_ar_iq as tNameAr, TermName_ku_iq as tNameKu,  
        EducGradeName_en_us as stageNameEn, EducGradeName_ar_iq as stageNameAr, EducGradeName_ku_iq as stageNameKu,  
        SessionName_en_us as sessionNameEn, SessionName_ar_iq as sessionNameAr, SessionName_ku_iq as sessionNameKu,  
        TermStatusName_en_us as lctStatusEn, TermStatusName_ar_iq as lctStatusAr, TermStatusName_ku_iq as lctStatusKu  
        from EducCenterTerm LCT 
            inner Join SessionTerm LST on LCT.SessionTermID = LST.SessionTermID 
            inner join lkupTerm T on T.TermID = LST.TermID 
            inner join EducGrade S on LST.EducGradeID = S.EducGradeID 
            inner join Session LS on LST.SessionID = LS.SessionID 
            inner join lkupTermStatus ST on LCT.EducCenterTermStatusID = ST.TermStatusID
        where  
            EducCenterTermObjectStatusID = 1 
            and EducCenterID = @EducCenterID 
            and EducCenterTermStatusID not in (5,6)
            and LS.EducTypeID = @EducType
            End  ;  

ALTER Procedure [dbo].[GetEducCentersForUsers](@UserId nvarchar%28128%29, @EducTypeID int) 
As 
    Begin 
        Declare @PersonID int Select @PersonID = Person_PersonID  from AspNetUsers where [Id] = @UserId 

```
    Select LC.EducCenterID as lcID, 
         LC.FacilitySchoolCenterStatusID as statusID, 
         EducCenterTypeID as typeID,  
         LC.EducCenterDetails_en_us as lcNameEn, 
         LC.EducCenterDetails_ar_iq as lcNameAr, 
         LC.EducCenterDetails_ku_iq as lcNameKu,  
         LC.SchoolGenderID as lcGenderID,
         C.FacilityName_en_us as cNameEn, 
         C.FacilityName_ar_iq as cNameAr, 
         C.FacilityName_ku_iq as cNameKu, 
         C.AddressID as cAddress, 
         AC.PlaceID as cPlace, 
         S.SchoolName_en_us as sNameEn, 
         S.SchoolName_ar_iq as sNameAr, 
         S.SchoolName_ku_iq as sNameKu, 
         S.AddressID as sAddress, 
         [AS].PlaceID as sPlace, 
         St.FacilitySchoolCenterStatusName_en_us as statusEn, 
         St.FacilitySchoolCenterStatusName_ar_iq as statusAr, 
         St.FacilitySchoolCenterStatusName_ku_iq as statusKu  
     from EducCenter LC  
         left outer join Facility C on LC.FacilityID = C.FacilityID 
         left outer join School S on LC.SchoolID = S.SchoolID 
         left outer join [Address] AC on C.AddressID = AC.AddressID 
         left outer join [Address] [AS] on S.AddressID = [AS].AddressID 
         inner join lkupFacilitySchoolCenterStatus St on LC.FacilitySchoolCenterStatusID = St.FacilitySchoolCenterStatusID 
     where LC.EducTypeID = @EducTypeID  
     and LC.EducCenterObjectStatusID = 1 End  ;  
```

Alter Procedure [dbo].[GetActiveEducCenterTerms](@EducCenterID int) 
As 
Begin 
    Select EducCenterTermID as lctID, 
           EducCenterTermStatusID as lctStatus, 
           EducCenterTermStartDate as startDate, 
           EducCenterTermEndDate as endDate, 
           EducCenterTermName_en_us as lctNameEn, 
           EducCenterTermName_ar_iq as lctNameAr, 
           EducCenterTermName_ku_iq as lctNameKu, 
           SessionTermName_en_us as lstNameEn, 
           SessionTermName_ar_iq as lstNameAr, 
           SessionTermName_ku_iq as lstNameKu, 
           TermName_en_us as tNameEn, 
           TermName_ar_iq as tNameAr, 
           TermName_ku_iq as tNameKu, 
           EducGradeName_en_us as stageNameEn, 
           EducGradeName_ar_iq as stageNameAr, 
           EducGradeName_ku_iq as stageNameKu, 
           SessionName_en_us as sessionNameEn, 
           SessionName_ar_iq as sessionNameAr, 
           SessionName_ku_iq as sessionNameKu,
           TermStatusName_en_us as lctStatusEn, 
           TermStatusName_ar_iq as lctStatusAr, 
           TermStatusName_ku_iq as lctStatusKu  
    from EducCenterTerm LCT 
    inner Join SessionTerm LST on LCT.SessionTermID = LST.SessionTermID 
    inner join lkupTerm T on T.TermID = LST.TermID 
    inner join EducGrade S on LST.EducGradeID = S.EducGradeID 
    inner join Session LS on LST.SessionID = LS.SessionID 
    inner join lkupTermStatus ST on LCT.EducCenterTermStatusID = ST.TermStatusID 
    where  EducCenterTermObjectStatusID = 1
    and EducCenterTermStatusID = 1 
    and EducCenterID = @EducCenterID End  ;

**Comment by DrJoeHage** [comment]
Getting errors

Msg 137, Level 15, State 2, Procedure GetEducCentersForUsers, Line 12

Must declare the scalar variable "@UserId".

Msg 137, Level 15, State 2, Procedure GetEducCentersForUsers, Line 39

Must declare the scalar variable "@EducTypeID".

**Comment by DrJoeHage** [comment]
Verified.
