### ISSUE TITLE
P3: Missing information in Sections listing affecting usability

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#477]
http://lsims.moe.gov.iq:8085/TermManagement/StageSections/Index

In the first column on the left, we should add "Session".
Then it will be followed by "Term".
Then, we should add "Education Center".

This way the user will know which Section is to be modified.

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
Verified.
