### ISSUE TITLE
P4: Center Management > Form needed to manage Facility Services available

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#48]
Center Management > Form needed to manage Facility Services available because a one to many relationship exists between each Facility and the services it provides.

**Comment by RaymondYounan** [comment]
Can you please elaborate. Where is the table that contains the data for the Facility Services?

**Comment by DrJoeHage** [comment]
FacilitySchoolBuildingService table.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that the manage facility services form is now available under the "Manage Building Service" column in the "Manage Facility" form.
**Please Note that the manage facility service column title and form name should be updated from "Manage Building Service" to "Manage Facility Service"**

**Comment by DrJoeHage** [comment]
Raymond, give me a chance to review this before you do anything.

**Comment by DrJoeHage** [comment]
We decided to keep Building Service for both schools and facilities.

**Comment by tannourynadine** [comment]
Verified that for "Facilities" and "Schools" the "Manage Building Service" is available under the "Manage Building Service" column in the "Manage Schools" and "Manage Facilities" forms.
