### ISSUE TITLE
P4: Center Management > Form needed to manage School Services available

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#49]
Center Management > Form needed to manage School Services available because a one to many relationship exists between each School and the services it provides.

**Comment by RaymondYounan** [comment]
Can you please elaborate. Where is the table that contains the data for the School Services?

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that the manage school services form is now available under the "Manage Building Service" column in the "Manage Schools" form.
**Please Note that the manage school service column title and form name should be updated from "Manage Building Service" to "Manage School Service"**

**Comment by DrJoeHage** [comment]
Raymond, give me a chance to review this before you do anything.

**Comment by DrJoeHage** [comment]
We decided to keep Building Service for both schools and facilities.

**Comment by tannourynadine** [comment]
Verified that for "Facilities" and "Schools" the "Manage Building Service" is available under the "Manage Building Service" column in the "Manage Schools" and "Manage Facilities" forms.
