### ISSUE TITLE
Manage Ministries

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#5]
Manage Ministries is missing from the UI.

**Comment by RaymondYounan** [comment]
Joe, 
You need to fix the table Ministry:
The Field MinistryObjectStatusID has the property "Is Identity" set to Yes while it should not be an identity column.
The field MinistryID has the property "Is Identity" set to No while it should be an identity column

**Comment by RaymondYounan** [comment]
Done, will be updated in the new release

**Comment by tannourynadine** [comment]
Verified that the Ministry form is now available under the "Application Administration" Sub-menu.
