### ISSUE TITLE
P2: Center Management > Error while creating new School

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#51]
Error in creating School: An error occurred while updating the entries. See the inner exception for details.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Schools > An error message is generated when the user selects a country different than "Iraq" while creating a new school.

**Steps to Reproduce**
-   Select Schools from the left navigation menu.
-   Click on the “Create” button.
-   Fill in all the information and select a country.

**Actual Result**
The following error message is generated when the user selects a country different than "Iraq" : “Error getting the Governorates:undefined”
**Expected Result**
No error message should be generated when the user selects a country different than "Iraq"

**Comment by DrJoeHage** [comment]
This needs to be deferred eventually if it applies to other than Iraq.

**Comment by RaymondYounan** [comment]
Done

**Comment by RaymondYounan** [comment]
Done.
As agreed, we removed all countries except Iraq

**Comment by tannourynadine** [comment]
Verified that no error message is generated and the user is able to create a new school, and only Iraq is available in the “Country” drop down menu.
