### ISSUE TITLE
P2: Student Management > Student Gender Preference form is missing

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#52]
Need a form to specify the Student's Gender Preference for Education Center Gender, as per FRS.

**Comment by DrJoeHage** [comment]
Just add a dropdown list to the Student Management form with values retrieved from the lkupEducCenterGender table. The values should be stored in the StudentGenderPreference table because this is a 1 to many relationship for the Student. For example, a Male student may have a preference for Male and Mixed gender.

**Comment by DrJoeHage** [comment]
This is a multi-select list or if not possible, do a form like the others shown in pop down menu under Student Management in the right pane.

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
Verified. Time for @tannourynadine to take screen shots.

**Comment by tannourynadine** [comment]
Updated the EACI FRS, EACI User Guide and LEMIS User Guide with updated screenshots.
