### ISSUE TITLE
P2: Student Management > Student Exam Records form is missing

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#53]
Form needed to enter/modify the exam records of a particular student.

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
Verified. Time for @tannourynadine to take screen shots.

**Comment by tannourynadine** [comment]
Updated the EACi FRS, EACI user guide and LEMIS user guide with updated screenshots.
