### ISSUE TITLE
System Administration > Form to manage Education Progression Path is missing

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#56]
Under System Administration, we need a Form to manage Education Progression Path, as per FRS.

**Comment by RaymondYounan** [comment]
Done.
Area: LookupsManagement
Controller: EducProgressionPath
Action: Index

**Comment by tannourynadine** [comment]
Verified that the "Education Progression Path" form is now available under the "System Administration" menu.
