### ISSUE TITLE
System Administration > Form to manage Education Stage Grades is missing

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#57]
Under System Administration, we need a Form to manage Education Stage Grades, as per FRS.

**Comment by RaymondYounan** [comment]
Done.
Area: LookupsManagement
Controller: EducationStageGrade
Action: Index

**Comment by tannourynadine** [comment]
Verified that the "Education Stage Grade" form is now available under the "System Administration" form.
