### ISSUE TITLE
P1: Student Management > Student Problem Creation is not saving Educ Grade

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#59]
Go to Student Management
Select student Iman Mahmoud
Modify Student Problem
Actual: Education Grade is set to Grade 1.
Expected: It was saved as Primary.
Change it to Primary and Save the problem.
Return and you will see that it reverted back to Grade 1.

**Comment by RaymondYounan** [comment]
Done
Duplicate of #164

**Comment by tannourynadine** [comment]
Verified the "Education Grade" field maintain the previously selected value in Edit mode.
