### ISSUE TITLE
Manage Departments

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#6]
Manage Departments is missing from the UI.

**Comment by RaymondYounan** [comment]
Joe,
You need to update the table Dept.
the column DeptID has the property "Is Identity" set to No while it should be set to Yes

**Comment by DrJoeHage** [comment]
Ok

Thanks,

Joe

**Comment by RaymondYounan** [comment]
Done, will be updated in the new release

**Comment by tannourynadine** [comment]
The management department form is now available in the user interface under the "Application Administrator" Sub-menu
