### ISSUE TITLE
P2: Student Management > Student Failure Reason form is missing

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#60]
Form needed to enter/modify the failure reasons of a particular student.

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
Verified. Time for @tannourynadine to take screen shots.

**Comment by tannourynadine** [comment]
- Verified that the Student Failure Reason Form is available in the UI.
- Updated the FRS and Guides with updated screenshots.
