### ISSUE TITLE
P2: Student Management > Student Dropout Reason form is missing

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#61]
Form needed to enter/modify the dropout reasons of a particular student.

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
Verified. Time for @tannourynadine to take screen shots.

**Comment by tannourynadine** [comment]
- Verified that the Student Drop out Reason Form is available in the UI .
- Updated the FRS and Guides with updated screenshots.
