### ISSUE TITLE
P2: Add Person form is missing from Application Administration menu

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#62]
Need to create a new Form for adding a Person.

**Comment by RaymondYounan** [comment]
Done.
Can be found under UserManagement/Person/Index

**Comment by tannourynadine** [comment]
Verified that the "Add Person" form is now available using the following link:UserManagement/Person/Index. **However, if you navigate to the Application Administration menu, the form is not displayed there.**

**Comment by DrJoeHage** [comment]
Added the option to the MENU table.
