### ISSUE TITLE
P1: Student Management > Missing Prior School field from Create/Edit Student form

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#63]
Student Management > Missing Prior School field from Create/Edit Student form.
There is only a field for the Education Center that the Student is getting assigned to.

**Comment by RaymondYounan** [comment]
DOne

**Comment by DrJoeHage** [comment]
Verified. Time for @tannourynadine to take screen shots.

**Comment by tannourynadine** [comment]
Updated the LEMIS and EACI user guides with updated screenshots.
