### ISSUE TITLE
P4: Center Management > Facility and School Names should be required fields

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#64]
If not, the drop downs with Names of Facilities and Schools will have blank values.
Facility and School tables need to be updated.

**Comment by DrJoeHage** [comment]
Should I just make the fields in the table NOT NULL?

**Comment by RaymondYounan** [comment]
This is one solution (The one I prefer), however this will oblige the people doing the data entry to enter the name of the school/facility in three languages.
Another solution can be that forcing the not null happens programmatically. 
Please let me know what you decide.

**Comment by DrJoeHage** [comment]
Let's do it at the database level. That way is much cleaner. I will update the table.

**Comment by DrJoeHage** [comment]
Hmm! I just checked and these fields are already set to NOT NULL in the database.
