### ISSUE TITLE
P2: Center Management > Unable to save New School for a country other than Iraq

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#66]
After entering data for a new school and attempting to save the new school, the following error message is displayed:

Error in creating School: An error occurred while updating the entries. See the inner exception for details.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
The user is able to create new school if it belongs to Iraq, **however** if the user selects a country different than the "Iraq", the following error message is generated:“Error getting the Governorates:undefined” and the user is not able to create the new school.

**Comment by RaymondYounan** [comment]
Duplicate of #51

**Comment by RaymondYounan** [comment]
Done.
As agreed we removed all countries except Iraq

**Comment by tannourynadine** [comment]
Verified that no error message is generated and the user is able to create a new school, and only the Iraq is available in the “Country” drop down menu.
