### ISSUE TITLE
Center Management > Must have 3 separate pages

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#67]
Manage Facility Administrators
Manage School Administrators
Manage Education Center Administrators

All use the same table.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
- Verified that the “Manage Literacy Centers Administrators” form can be accessed from the manage education centers section.
- Verified that the “Manage Facility Administrators” form can be accessed from the manage facilities section.
- Verified that the “Manage School Administrators” form can be accessed from the manage schools section.
