### ISSUE TITLE
P1: Reports > Clicking on a link from the left navigation menu redirects the user to a different report.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#68]
**Steps to Reproduce**
1- Click on the Reports menu.
2- Click on the "Number of Centers in the Directorates by Stage, Student Gender and Type of Schedule"

**Actual Result**
The "Number of Centers in the Governorates by Autonomy, Environment, Construction Material, and Ownership" report is displayed instead of the "Number of Centers in the Directorates by Stage, Student Gender and Type of Schedule" report.

**Expected Result**
The "Number of Centers in the Directorates by Stage, Student Gender and Type of Schedule" report should be displayed when the user clicks on the the "Number of Centers in the Directorates by Stage, Student Gender and Type of Schedule" link available in the left navigation menu.

**Note:**
This issue is also reproducible for  the below reports:
- Number of Centers in the Governorates by Stage, Student Gender and Type of Schedule
- Number of Centers in the Governorates by autonomy Environment, Construction Material and Ownership.
- Number of centers in the Directorates by Independence, Environment, Construction Material and Ownership.
- Number of Students enrolled in the Governorates by enrollment type and gender.
- Number of Students enrolled in the Directorates by enrollment type and gender.

**Comment by RaymondYounan** [comment]
@DrJoeHage, the menu items should be updated
MenuID 301: MenuAction ==> GetByStageGenderSchedule
MenuID 302: MenuAction ==> GetByStageGenderSchedule

MenuID 316: MenuAction ==> GetByNewOrOld
MenuID 317: MenuAction ==> GetByNewOrOld
