### ISSUE TITLE
P2: Facilities > The user is not able to create a new facility.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#71]
**Steps to Reproduce**
1- Select Facilities from the left navigation menu.
2- Click on the "Create Facility" button.
3- Enter all the required information and then click on the "Save" button.

**Actual Result**
An error message is generated when the user clicks on the "Save Facility" button.

**Expected Result**
No error message should be generated and the user should be able to create a new facility.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Tested the "Create a facility" functionality and verified that the user is able to create a new facility **However, creating a facility that belongs to country different than Iraq generates the following error: "Error getting the Governorates:undefined"**

**Comment by DrJoeHage** [comment]
You cannot assume that there is a governorate for a given country. Lebanon for example has Mohafazat.

**Comment by RaymondYounan** [comment]
Done. As agreed we removed all countries except Iraq

**Comment by tannourynadine** [comment]
Verified that the user is able o create a new Facility, and only "Iraq" is available in the country drop down menu.
