### ISSUE TITLE
Facilities > Manage Facility Administrators > An error message should be generated when the user clicks on the "Delete" button.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#73]
An error message is generated when the user clicks on the "Delete" button.
Please Note that a popup confirmation dialog is needed when the user clicks on the "Delete" button to enable the user to choose between canceling or confirming the deletion process.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
- Verified that no error message is generated when the user clicks on the "Delete" button.
- Verified that a popup confirmation dialog is displayed when the user clicks on the "Delete" button that enables the user to choose between canceling or confirming the deletion process.
- Verified that the user is able to create a new administrator.
- Verified that the user is able to modify the information related to an administrator.
