### ISSUE TITLE
Facilities > A popup dialog is generated when the user clicks on the "Save Center Administrator" button while creating a new Facility Administrator.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#74]
**Steps to Reproduce**
1- Select Facilities from the left navigation menu.
2- Click on the "Manage Facility Administrators" button.
3- Click on the "Create Center Administrator" button.
4- Enter a start, end and certification dates and then click on the "Save Center Administrator" button.

**Actual Result**
A popup dialog is generated for the start, end and certification dates when the user clicks on the "Save Center Administrator" button while creating a new Facility Administrator. (See attached screenshot)
*\* Note:*\* 
This issue is also reproducible for the School Administrators.

**Expected Result**
No popup dialog should be generated.

![manage-facility-admin](https://cloud.githubusercontent.com/assets/3637417/5546850/fd790cf2-8b54-11e4-9105-b103d8513350.png)

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that no popup dialogs are generated for the start, end and certification dates when the user clicks on the "Save Center Administrator" button while creating a new Facility and School Administrators.
