### ISSUE TITLE
P4: Schools > Manage School Administrators > Incorrect Page Title and Create button text is displayed.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#77]
Since the user is managing school administrators the page title and create button should be updated from "Manage Center Administrators" to "Manage School Administrators" and the create button should be updated from "Create Center Administrators" to "Create School Administrators".

**Comment by RaymondYounan** [comment]
Done

**Comment by DrJoeHage** [comment]
Fixed.

**Comment by tannourynadine** [comment]
- Verified that the "Manage Center Administrators" is updated to "Manage School Administrators".
- Verified that the Create button is updated from "Create Center Administrator" to "Create School Administrator".
