### ISSUE TITLE
P4: Schools > Manage School Administrators > Incorrect Page Titles are displayed at the Create a school administrator popup dialog

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#78]
Since the user is managing school administrators the page titles and create button should be updated from "Manage Center Administrators" to "Manage school Administrators" and the create button should be updated from "Save Center Administrator" to "Save School Administrator". (See attached Screenshot)
**Note:** This issue is also reproducible for the Edit School Administrators

![school-admin](https://cloud.githubusercontent.com/assets/3637417/5547225/cb459df4-8b5e-11e4-980b-a5f964aebad0.png)

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
- Verified that the "Manage Center Administrators" is updated to "Manage School Administrators" at the Create/Edit Administrator page.
- Verified that the Create and the Edit buttons are updated from "Save Center Administrator" to "Save School Administrator".
