### ISSUE TITLE
Manage Places

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#8]
Manage Places generates error when clicked under System Administration.

Error.
An error occurred while processing your request.

http://emis.joe.me:8088/PlaceManagement/Place/Index

**Comment by RaymondYounan** [comment]
Resolved

**Comment by tannourynadine** [comment]
- Verified that no error message is generated when the user clicks on the "Places" link available under the "System Administration" sub-menu.
- Verified that the user is able to create, modify and delete a place.
