### ISSUE TITLE
Schools > An error message is generated when the user tries to delete a School.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#81]
**Steps to Reproduce**
- Select Schools from the left navigation menu.
- Select a school and then click on the “Delete” button.

**Actual Result**
An error message is generated when the user tries to delete a School. (See attached Screenshot)
**Expected Result**
A popup delete confirmation dialog should be generated and the user should be able to delete the selected school.

![school-delete](https://cloud.githubusercontent.com/assets/3637417/5594715/5335567a-9260-11e4-94cd-51cf3c088b23.png)

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that no error message is generated when the user tries to delete a School and a popup confirmation dialog is generated enabling the user to choose between canceling or confirming the deletion process.
