### ISSUE TITLE
Facilities > Manage Administrators > An error message is generated when the user tries to create a new facility administrator and leaves the “Certification Date” field empty.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#83]
No error message should be generated when the user tries to create a new facility administrator and leaves the “Certification Date” field empty. There is no need to enter a date for a certification if the user doesn’t have any certifications and leaves the "Has Certification" field unchecked.

The following is the error generated: "Error in creating Center Admin:String reference not set to an instance of a String. Parameter name: s"

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
No error message is generated when the user creates a new facility administrator and leaves the “Certification Date” field empty.
