### ISSUE TITLE
P2: Application Administrator > Departments > An error message is generated when the user selects a Directorate from the list of available options for the "Directorate" field while creating a new department.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#84]
The following error message is generated when the user selects a Directorate from the list of available options for the "Directorate" field while creating a new department: "Error getting the Governorates: undefined"

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that the user is able to Create, Edit and Delete a Department and no error message is generated for the "Directorate" field.
