### ISSUE TITLE
System Admninistration > Places > No popup delete confirmation dialog is generated when the user clicks on the "Delete" button.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#85]
A popup confirmation dialog should be generated when the user clicks on the "Delete" button to enable the user to choose between canceling or confirming the deletion process.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that a popup delete confirmation dialog is generated when the user clicks on the "Delete" button and the user is able to choose between canceling or confirming the deletion process.
