### ISSUE TITLE
P4: Application Administration > Directorate >  An error message is generated when the user creates a new directorate that doesn’t belong to Iraq.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#86]
**Steps to Reproduce**
-   Select Application Administration > Directorate from the left navigation menu.
-   Click on the “Create Directorate” button.
-   Fill in all the information and for the country field, select a country different than “Iraq”.

**Actual Result**
The following error message is generated when the user selects a country different than “Iraq”: “Error getting the Governorates:undefined”

**Notes**
- If the directorate belongs to Iraq and to a district that doesn't have a sub-district, the following error message is generated: "Error in creating Directorate:Input string was not in a correct format." and the directorate cannot be created.
- This issue is also reproducible when the user tries to update a directorate belonging to Iraq to a different country.

**Expected Result**
No error message should be generated when the user selects a country different than “Iraq” and the directorate should be created with no issues.

**Comment by RaymondYounan** [comment]
Joe,

Since we have no data for countries other than Iraq, the drop down lists will not be generated.
Can you please specify how to solve this?

Thanks

**Comment by DrJoeHage** [comment]
This is a corner case. But I think I will add the information of Lebanon to the seed data.

**Comment by DrJoeHage** [comment]
I added Lebanon information but we need to defer all Non-Iraq related issues.
We will make the ObjectStatusID in the tables for non-Iraq Places set to 0.
You will need to only show Iraq in the drop downs of Addresses except for Nationality you will show all the countries.

**Comment by DrJoeHage** [comment]
Decision was made to keep all countries ObjectStatusID set to 1 and Ray will filter out all countries except Iraq from all dropdown lists except the Country of Citizenship field.

**Comment by RaymondYounan** [comment]
Done.
As agreed, we removed all countries except Iraq

**Comment by tannourynadine** [comment]
Verified that the country drop down only contains Iraq and no error is generated when the user creates a new Directorate.
