### ISSUE TITLE
Centers > Facilities >  Manage Building Service > Incorrect page title and button texts are displayed

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#87]
Please update the below page titles and content:
- Facility Management > Facility Management table > Update "Manage Building Service" column title and content to "Manage Facility Service".
- Facility Management > Manage Building Service > Page title from “Manage Building Service” to “Manage Facility Service”.
- Facility Management > Manage Building Service > Create a new service text button from “Create Building Service” to “Create Facility Service”.
- Manage Service popup dialogue> Page title from “Manage Building Service” to “Manage Facility Service”.
- Manage Service popup dialogue> Content from “Create Building Service” to “Create Facility Service”.
- Manage Service popup dialogue> Button  from “Save Building Service” to “Save Facility Service”.
  (See attached screenshots)

![facility-building-services](https://cloud.githubusercontent.com/assets/3637417/5611808/1282e9a0-94d4-11e4-8753-b79e2b7ec2e9.png)
![facility-building-services-2](https://cloud.githubusercontent.com/assets/3637417/5611809/12a2e2d2-94d4-11e4-89c1-0d57348e3084.png)
![facility-building-services-4](https://cloud.githubusercontent.com/assets/3637417/5611886/25b9d03c-94d5-11e4-9a06-09f0f33e896f.png)

**Comment by RaymondYounan** [comment]
Joe,

What do you want to do with this?

**Comment by DrJoeHage** [comment]
Schools and Facilities have buildings. The buildings have elevators or bathrooms or handicapped access etc. So, Building Service should apply to both schools and facilities.
