### ISSUE TITLE
Centers > Facilities >  Manage Building Service > The facility name doesn’t appear under the “Facility” column.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#88]
After the user creates a new service and clicks on the “Save Building Service” button, the service appears in the manage service table with no name displayed under the facility column. (See attached screenshot)
Please note that refreshing the page, removes the issue.

![facility-building-services-3](https://cloud.githubusercontent.com/assets/3637417/5611909/941fbda2-94d5-11e4-8232-3be214301433.png)

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
- Verified that when the user creates or updates a facility building service, the facility name appears under the Facility column.
- Verified that when the user updates a Facility name at the "Facility Management" form, the facility name gets updated too at the "Manage Building Service" form.
