### ISSUE TITLE
Manage School Days

### ISSUE THREAD

**Issue by DrJoeHage** [RaymondYounan/LEMIS#9]
Under System Administration, School Day Management has several issues:
1. The list is not displaying the names of the days which are to be pulled from the lkupDayofWeek table.
2. The EducType field is missing from the list.
3. There is no ability to Add a New School day for any EducType. The seeded values are only for EducType 2 (Literacy) and 3 (ALP).

**Comment by RaymondYounan** [comment]
Done.
Area: LookupsManagement
Controller: SchoolDay
Action: Index

**Comment by tannourynadine** [comment]
- Verified that the user is able to create, modify and delete a school day and correct information is displayed.
- Verified that the “Day of the Week” dropdown list contains the names of all week days. (From Monday till Sunday).
- Verified that the “Education Type” dropdown list contains the following education types:  Regular, Literacy, Accelerating Learning Program, Out of School Children and College.
