### ISSUE TITLE
P4: Centers > Schools >  Manage Building Service > Incorrect page title and button texts are displayed

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#90]
Please update the below page titles and content:
- School Management > School Management table >  Please replace "Manage Building Service" column title and content with "Manage School Service".

![manage-school](https://cloud.githubusercontent.com/assets/3637417/5612088/f6cd6632-94d7-11e4-8b06-1f94ce495e40.png)
- School Management > Manage Building Service > Please replace "Building" with "School". See attached screenshot.

![manage-school-1](https://cloud.githubusercontent.com/assets/3637417/5612090/05384fca-94d8-11e4-83eb-b2a30a09e62f.png)
- Manage Building Service > Create a new service > Please replace "Building" with "School". See attached screenshot.

![manage-school-2](https://cloud.githubusercontent.com/assets/3637417/5612094/133538b8-94d8-11e4-9062-0b19aa3d0d7d.png)

**Comment by RaymondYounan** [comment]
Joe,

What do you want to do with this?

**Comment by DrJoeHage** [comment]
Services are related to buildings inside a school or facility. So, it should stay the same. I thought this was clear in the FRS. If not, Nadine, please update the FRS and User Guide.

**Comment by DrJoeHage** [comment]
Should leave it AS IS. Nadine, please ensure FRS and User Guide reflects this.

**Comment by tannourynadine** [comment]
Thanks for the clarification, I'll check the FRS and the User Guide and update them accordingly.

**Comment by tannourynadine** [comment]
Updated the FRS and Admin/User guides.
