### ISSUE TITLE
P2: Application Administration > Ministry >  An error message is generated when the user tries to update a ministry

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#91]
The following error message is generated when the user tries to update a ministry: “Error updating the Ministry:Value cannot be null. Parameter name: String”.

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that no error message is generated when the user updates a Ministry, **However, if the user selects a country different than Iraq, the following error message is generated: "Error getting the Governorates:undefined"**

**Comment by RaymondYounan** [comment]
This is the case since only Iraq has Governerates. Data for other countries does not exist, this is why you are facing this issue

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that the user is able to create, modify and delete a ministry and no error message is generated.
