### ISSUE TITLE
P2: Log out button only works from home page, It should work from any page.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#93]
An error message is generated when the user tries to log out from the application from a page different than the home page.

**Comment by RaymondYounan** [comment]
Done.
Still need to fix the logoff

**Comment by tannourynadine** [comment]
Verified that the log out button works across different pages of the application

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that the log out button works across different pages of the application
