### ISSUE TITLE
P2: Application Administration > Grade Section > Error messages are generated when the user tries to create a new section

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#94]
**Steps to Reproduce**
-   Select Application Administration > Grade Section from the left navigation menu.
-   Click on the “Create” button.
-   Fill in all the information.

**Actual Result**
Error messages are generated when the user clicks on the “Save” button while creating a new section. (See attached screenshot)

**Expected Result**
No error messages should be generated when the user clicks on the “Save” button while creating a new section. 

![create-section](https://cloud.githubusercontent.com/assets/3637417/5625821/e2eee088-958a-11e4-8303-8cff687bead9.png)

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that no error messages are generated when the user clicks on the “Save” button while creating a new section.
