### ISSUE TITLE
P2: Application Administration > Grade Section > An error message is generated when the user tries to delete a section

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#95]
**Steps to Reproduce**
-   Select Application Administration > Grade Section from the left navigation menu.
-   Select an existing section and then click on the “Delete” button.

**Actual Result**
An error message is generated when the user tries to delete a section. (See attached screenshot)

**Expected Result**
No error message should be generated when the user tries to delete a section and the section should be deleted successfully. 

![delete-section](https://cloud.githubusercontent.com/assets/3637417/5625938/e7c4918c-958c-11e4-8954-f468dbdc9355.png)

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that no error message is generated when the user tries to delete a section and the section is deleted successfully.
