### ISSUE TITLE
Application Administration > Grade Section > Duplicate page titles are displayed at the delete section page

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#96]
**Steps to Reproduce**
-   Select Application Administration > Grade Section from the left navigation menu.
-   Select an existing section and then click on the “Delete” button.

**Actual Result**
At the delete section page duplicate page titles are displayed. (See attached screenshot)

**Expected Result**
At the delete section page one page title should be displayed.

![delete-section-2](https://cloud.githubusercontent.com/assets/3637417/5626118/65ea9c58-958f-11e4-94e7-ba69ed252844.png)

**Comment by RaymondYounan** [comment]
Done

**Comment by tannourynadine** [comment]
Verified that at the delete section page only one page title is displayed.
