### ISSUE TITLE
P1: Application Administration > Exam > Incorrect Arabic and Kurdish descriptions are displayed for an exam after the page gets refreshed

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#97]
**Steps to Reproduce**
- Select Application Administration > Exam from the left navigation menu.
- Click on the “Create New Exam”  button, fill in all the information and then click on the “Save” button.
- The exam is displayed in front of the user with the correct Arabic and Kurdish descriptions.
- Refresh the page.

**Actual Result**
Incorrect Arabic and Kurdish descriptions are displayed for an exam after the page gets refreshed. (See attached screenshot)

**Expected Result**
Correct Arabic and Kurdish descriptions should be displayed for an exam even when the page gets refreshed.

![exam](https://cloud.githubusercontent.com/assets/3637417/5626450/37d89ad6-9594-11e4-9ec2-e41f81c61b19.png)

**Comment by Rfarran** [comment]
Done

**Comment by tannourynadine** [comment]
I was not able to verify this issue.

While creating a New Exam, the user is not able to chose a Term and therefore when he clicks on the "Save" button, he gets the following error: "Error saving exam details:The INSERT statement conflicted with the FOREIGN KEY constraint "FK_Exam_SessionTerm". The conflict occurred in database "EMIS", table "dbo.SessionTerm", column 'SessionTermID'. The statement has been terminated."

**Comment by tannourynadine** [comment]
- Verified that the user is able to create and modify an exam.
- Verified that correct Arabic and Kurdish descriptions are displayed for an exam.
