### ISSUE TITLE
P3: Application Administration > Exam > When the user clicks on the on button to show Postponed, Completed or Canceled exams, the Pending exams are always displayed.

### ISSUE THREAD

**Issue by tannourynadine** [RaymondYounan/LEMIS#98]
**Steps to Reproduce**
- Select Application Administration > Exam from the left navigation menu.
- Click on the “ON”  button to only show Postponed exams. 

**Actual Result**
- When the user clicks on the on button to show Postponed exams, the Pending exams are always displayed. (See attached screenshot)
- This issue is also reproducible for canceled and completed exams.

**Expected Result**
When the user clicks on the on button to show Postponed exams, the Pending exams should not be displayed.

![exam-1](https://cloud.githubusercontent.com/assets/3637417/5626728/15b2ece6-9598-11e4-8881-223a88e9564d.png)

**Comment by DrJoeHage** [comment]
This is an acceptable behavior.
